/**
 *  Codasip s.r.o.
 * 
 *  CONFIDENTIAL
 * 
 *  Copyright 2024 Codasip s.r.o.
 * 
 *  All Rights Reserved.
 *  This file is part of the Codasip Studio product. No part of the Studio product, including this
 *  file, may be use, copied, modified, or distributed except in accordance with the terms contained
 *  in Codasip license agreement under which you obtained this file.
 * 
 *  \file
 *  \date    2024-11-27
 *  \author  Codasip (c) HW generator
 *  \version 9.4.1
 *  \brief   Contains module definition of the 'codix_berkelium_ca_core_execute_stage_t' CodAL module.
 *  \note    
 *           Generated for Codasip Ltd.
 *           
 *           Model version: 5.0.3
 *           
 *           Model configuration: l31-32IMFCB-UPTIDpbid
 *           Tools version: b'9.4.1'
 *           Evaluation mode: off
 *           Platform: centos.7.x86_64
 *           All Rights Reserved.
 *           
 *           If you require any assistance submit a support request: support@codasip.com
 *           
 */

module codix_berkelium_ca_core_execute_stage_t #(
    parameter [31:0] nmi_handler_p = 32'h20000004,
    parameter [31:0] itcm_size_p = 32'h00004000,
    parameter [31:0] itcm_baddr_p = 32'h02000000,
    parameter [31:0] dtcm_size_p = 32'h00004000,
    parameter [31:0] dtcm_baddr_p = 32'h03000000,
    parameter [31:0] cache_base_p = 32'h00010000,
    parameter [31:0] hart_id_p = 32'h00000000,
    parameter [31:0] pma_base0_p = 32'h20000000,
    parameter [31:0] pma_mask0_p = 32'hffe00000,
    parameter [15:0] pma_enable_p = 16'h003f,
    parameter [31:0] pma_base1_p = 32'h70010000,
    parameter [31:0] pma_mask1_p = 32'hffffff00,
    parameter [31:0] pma_base2_p = 32'h00020000,
    parameter [31:0] pma_mask2_p = 32'hfffffff0,
    parameter [31:0] pma_base3_p = 32'h00010000,
    parameter [31:0] pma_mask3_p = 32'hfffffe00,
    parameter [31:0] pma_base4_p = 32'h02000000,
    parameter [31:0] pma_mask4_p = 32'hffffc000,
    parameter [31:0] pma_base5_p = 32'h03000000,
    parameter [31:0] pma_mask5_p = 32'hffffc000,
    parameter [31:0] pma_base6_p = 32'h00000000,
    parameter [31:0] pma_mask6_p = 32'h00000000,
    parameter [31:0] pma_base7_p = 32'h00000000,
    parameter [31:0] pma_mask7_p = 32'h00000000,
    parameter [31:0] pma_base8_p = 32'h00000000,
    parameter [31:0] pma_mask8_p = 32'h00000000,
    parameter [31:0] pma_base9_p = 32'h00000000,
    parameter [31:0] pma_mask9_p = 32'h00000000,
    parameter [31:0] pma_base10_p = 32'h00000000,
    parameter [31:0] pma_mask10_p = 32'h00000000,
    parameter [31:0] pma_base11_p = 32'h00000000,
    parameter [31:0] pma_mask11_p = 32'h00000000,
    parameter [31:0] pma_base12_p = 32'h00000000,
    parameter [31:0] pma_mask12_p = 32'h00000000,
    parameter [31:0] pma_base13_p = 32'h00000000,
    parameter [31:0] pma_mask13_p = 32'h00000000,
    parameter [31:0] pma_base14_p = 32'h00000000,
    parameter [31:0] pma_mask14_p = 32'h00000000,
    parameter [31:0] pma_base15_p = 32'h00000000,
    parameter [31:0] pma_mask15_p = 32'h00000000,
    parameter [1:0] pma_cfg15_p = 2'h0,
    parameter [1:0] pma_cfg14_p = 2'h0,
    parameter [1:0] pma_cfg13_p = 2'h0,
    parameter [1:0] pma_cfg12_p = 2'h0,
    parameter [1:0] pma_cfg11_p = 2'h0,
    parameter [1:0] pma_cfg10_p = 2'h0,
    parameter [1:0] pma_cfg9_p = 2'h0,
    parameter [1:0] pma_cfg8_p = 2'h0,
    parameter [1:0] pma_cfg7_p = 2'h0,
    parameter [1:0] pma_cfg6_p = 2'h0,
    parameter [1:0] pma_cfg5_p = 2'h2,
    parameter [1:0] pma_cfg4_p = 2'h2,
    parameter [1:0] pma_cfg3_p = 2'h0,
    parameter [1:0] pma_cfg2_p = 2'h0,
    parameter [1:0] pma_cfg1_p = 2'h0,
    parameter [1:0] pma_cfg0_p = 2'h3,
    parameter [31:0] progbuf_base_p = 32'h00020000
) (
    input  logic execute_stage_div_s_div_ce_i_ICLK,
    input  logic execute_stage_fpu_add_sub_s_add_sub_ce_ICLK,
    input  logic execute_stage_fpu_float2int_s_f2i_ce_ICLK,
    input  logic execute_stage_fpu_fmul_s_fmul_ce_ICLK,
    input  logic execute_stage_fpu_fused_s_fused_ce_ICLK,
    input  logic execute_stage_fpu_int2float_s_i2f_ce_ICLK,
    input  logic execute_stage_fpu_sqrt_div_s_sqrt_div_ce_ICLK,
    input  logic execute_stage_lsu_s_load_ce_ICLK,
    input  logic execute_stage_lsu_s_lsu_ce_ICLK,
    input  logic execute_stage_lsu_s_store_ce_ICLK,
    input  logic r_wfi_ce_ICLK,
    input  logic s_fpu_ce_ICLK,
    input  logic RST,
    input  logic control_fpu_CONTROL_CLEAR_Q,
    input  logic control_fpu_CONTROL_STALL_Q,
    input  logic control_fpu_ROB_CLEAR_Q,
    input  logic fetch_stage_ifu_s_bus_busy_o_Q,
    input  logic [31:0] i1_if_cpu_ldst_HRDATA,
    input  logic i1_if_cpu_ldst_HREADY,
    input  logic i1_if_cpu_ldst_HRESP,
    input  logic [31:0] ira_r_return_address_D,
    input  logic ira_r_return_address_WE,
    input  logic p_dtcm_en_Q,
    input  logic [127:0] p_int_Q,
    input  logic p_itcm_en_Q,
    input  logic p_msip_Q,
    input  logic p_mtip_Q,
    input  logic [31:0] p_nmi_mtval_Q,
    input  logic p_nmi_Q,
    input  logic [63:0] perf_r_mhpmcounter10_Q,
    input  logic [63:0] perf_r_mhpmcounter12_Q,
    input  logic [63:0] perf_r_mhpmcounter13_Q,
    input  logic [63:0] perf_r_mhpmcounter14_Q,
    input  logic [63:0] perf_r_mhpmcounter15_Q,
    input  logic [63:0] perf_r_mhpmcounter3_Q,
    input  logic [63:0] perf_r_mhpmcounter4_Q,
    input  logic [63:0] perf_r_mhpmcounter5_Q,
    input  logic [63:0] perf_r_mhpmcounter6_Q,
    input  logic [63:0] perf_r_mhpmcounter9_Q,
    input  logic pipe_add_sub_COMPUTE_CLEAR_Q,
    input  logic pipe_add_sub_COMPUTE_STALL_Q,
    input  logic pipe_add_sub_POSTNORM_CLEAR_Q,
    input  logic pipe_add_sub_POSTNORM_STALL_Q,
    input  logic pipe_add_sub_ROUNDING_CLEAR_Q,
    input  logic pipe_add_sub_ROUNDING_STALL_Q,
    input  logic pipe_f2i_F2I_CLEAR_Q,
    input  logic pipe_f2i_F2I_STALL_Q,
    input  logic pipe_fmul_MUL_CLEAR_Q,
    input  logic pipe_fmul_POSTNORM1_CLEAR_Q,
    input  logic pipe_fmul_POSTNORM2_CLEAR_Q,
    input  logic pipe_fmul_ROUNDING_CLEAR_Q,
    input  logic pipe_fused_ADDSUB_CLEAR_Q,
    input  logic pipe_fused_POSTNORM_ADDSUB_CLEAR_Q,
    input  logic pipe_fused_POSTNORM_MUL1_CLEAR_Q,
    input  logic pipe_fused_POSTNORM_MUL2_CLEAR_Q,
    input  logic pipe_fused_PRENORM_ADDSUB_CLEAR_Q,
    input  logic pipe_fused_ROUNDING_CLEAR_Q,
    input  logic pipe_fused_WAIT_MUL_CLEAR_Q,
    input  logic pipe_i2f_COMPUTE_CLEAR_Q,
    input  logic pipe_i2f_COMPUTE_STALL_Q,
    input  logic pipe_i2f_ROUNDING_CLEAR_Q,
    input  logic pipe_i2f_ROUNDING_STALL_Q,
    input  logic pipe_sqrt_div_SQRT_DIV_CLEAR_Q,
    input  logic pl_lsu_FIN_CLEAR_Q,
    input  logic pl_lsu_FIN_STALL_Q,
    input  logic [31:0] r_csr_dcsr_Q,
    input  logic [31:0] r_csr_dpc_Q,
    input  logic [31:0] r_csr_fcsr_Q,
    input  logic [31:0] r_csr_mcause_Q,
    input  logic [31:0] r_csr_mcounteren_Q,
    input  logic [31:0] r_csr_mcountinhibit_Q,
    input  logic [63:0] r_csr_mcycle_Q,
    input  logic r_csr_mdtcmen_Q,
    input  logic [31:0] r_csr_mepc_Q,
    input  logic [31:0] r_csr_mexcause_Q,
    input  logic [31:0] r_csr_mie_Q,
    input  logic [63:0] r_csr_minstret_Q,
    input  logic [31:0] r_csr_mip_Q,
    input  logic r_csr_mitcmen_Q,
    input  logic [31:0] r_csr_mpicflag1_Q,
    input  logic [31:0] r_csr_mpicflag2_Q,
    input  logic [31:0] r_csr_mpicflag3_Q,
    input  logic [31:0] r_csr_mpicflag_Q,
    input  logic [31:0] r_csr_mpicmask1_Q,
    input  logic [31:0] r_csr_mpicmask2_Q,
    input  logic [31:0] r_csr_mpicmask3_Q,
    input  logic [31:0] r_csr_mpicmask_Q,
    input  logic [31:0] r_csr_mscratch_Q,
    input  logic [31:0] r_csr_mstatus_Q,
    input  logic [31:0] r_csr_mtval_Q,
    input  logic [31:0] r_csr_mtvec_Q,
    input  logic [31:0] r_csr_pmpaddr0_Q,
    input  logic [31:0] r_csr_pmpaddr10_Q,
    input  logic [31:0] r_csr_pmpaddr11_Q,
    input  logic [31:0] r_csr_pmpaddr12_Q,
    input  logic [31:0] r_csr_pmpaddr13_Q,
    input  logic [31:0] r_csr_pmpaddr14_Q,
    input  logic [31:0] r_csr_pmpaddr15_Q,
    input  logic [31:0] r_csr_pmpaddr1_Q,
    input  logic [31:0] r_csr_pmpaddr2_Q,
    input  logic [31:0] r_csr_pmpaddr3_Q,
    input  logic [31:0] r_csr_pmpaddr4_Q,
    input  logic [31:0] r_csr_pmpaddr5_Q,
    input  logic [31:0] r_csr_pmpaddr6_Q,
    input  logic [31:0] r_csr_pmpaddr7_Q,
    input  logic [31:0] r_csr_pmpaddr8_Q,
    input  logic [31:0] r_csr_pmpaddr9_Q,
    input  logic [31:0] r_csr_pmpcfg0_Q,
    input  logic [31:0] r_csr_pmpcfg1_Q,
    input  logic [31:0] r_csr_pmpcfg2_Q,
    input  logic [31:0] r_csr_pmpcfg3_Q,
    input  logic [31:0] r_csr_tcontrol_Q,
    input  logic [31:0] r_csr_tdata1_r_Q,
    input  logic [31:0] r_csr_tdata2_r_Q,
    input  logic [31:0] r_csr_tselect_Q,
    input  logic [3:0] r_ex1_fu_Q,
    input  logic [31:0] r_ex1_instr_addr_Q,
    input  logic r_ex1_is_rvc_Q,
    input  logic [5:0] r_ex1_rd_addr_Q,
    input  logic [31:0] r_ex_bp_addr_Q,
    input  logic r_ex_bp_taken_Q,
    input  logic [11:0] r_ex_csr_addr_Q,
    input  logic [31:0] r_ex_exc_tval_Q,
    input  logic [4:0] r_ex_exc_type_Q,
    input  logic r_ex_exc_valid_Q,
    input  logic [5:0] r_ex_fpu_op_Q,
    input  logic [3:0] r_ex_fu_Q,
    input  logic [1:0] r_ex_fu_s1_source_Q,
    input  logic [1:0] r_ex_fu_s2_source_Q,
    input  logic [1:0] r_ex_fu_s3_source_Q,
    input  logic [31:0] r_ex_imm_Q,
    input  logic [31:0] r_ex_instr_addr_Q,
    input  logic r_ex_instr_valid_Q,
    input  logic r_ex_is_rvc_Q,
    input  logic [31:0] r_ex_lsu_addr_Q,
    input  logic [7:0] r_ex_op_Q,
    input  logic [5:0] r_ex_rd_addr_Q,
    input  logic [2:0] r_ex_rm_Q,
    input  logic [5:0] r_ex_rs1_addr_Q,
    input  logic [5:0] r_ex_rs2_addr_Q,
    input  logic [5:0] r_ex_rs3_addr_Q,
    input  logic r_nmi_i_Q,
    input  logic [31:0] r_nmi_mtval_Q,
    input  logic r_nmi_source_Q,
    input  logic [1:0] r_prv_Q,
    input  logic r_reset_init_Q,
    input  logic [31:0] r_syscall_addr_Q,
    input  logic r_wfi_ce_Q,
    input  logic [31:0] rf_fr_r1_Q,
    input  logic [31:0] rf_fr_r2_Q,
    input  logic [31:0] rf_fr_r3_Q,
    input  logic [31:0] rf_gpr_r1_Q,
    input  logic [31:0] rf_gpr_r2_Q,
    input  logic s_dm_active_Q,
    input  logic s_dm_halt_Q,
    input  logic s_dm_progbuf_en_Q,
    input  logic s_eviction_error_Q,
    input  logic s_ex_bp_restart_Q,
    input  logic s_ex_branch_miss_Q,
    input  logic [31:0] s_ex_branch_target_addr_Q,
    input  logic s_ex_fpu_busy_Q,
    input  logic s_ex_stall_Q,
    input  logic s_flush_Q,
    input  logic [5:0] s_rd0_addr_Q,
    input  logic [31:0] s_rd0_data_Q,
    input  logic s_rd0_we_Q,
    input  logic s_rd0_write_Q,
    input  logic [5:0] s_rd1_addr_Q,
    input  logic [31:0] s_rd1_data_Q,
    input  logic s_rd1_we_Q,
    input  logic s_rd1_write_Q,
    output logic bru_s_branch_bht_update_o_Q,
    output logic bru_s_is_jump_o_Q,
    output logic [31:0] bru_s_rd_data_o_Q,
    output logic control_fpu_CONTROL_CLEAR_D,
    output logic control_fpu_CONTROL_STALL_D,
    output logic control_fpu_ROB_CLEAR_D,
    output logic [31:0] crf_s_csr_addr_o_Q,
    output logic crf_s_csr_valid_o_Q,
    output logic [12:0] crf_s_hpm_inhibit_o_Q,
    output logic crf_s_perf_inhibit_o_Q,
    output logic [31:0] crf_s_trap_addr_o_Q,
    output logic crf_s_trap_valid_o_Q,
    output logic div_s_div_ce_i_Q,
    output logic fpu_add_sub_s_add_sub_ce_Q,
    output logic fpu_float2int_s_f2i_ce_Q,
    output logic fpu_fmul_s_fmul_ce_Q,
    output logic fpu_fused_s_fused_ce_Q,
    output logic fpu_int2float_s_i2f_ce_Q,
    output logic fpu_sqrt_div_s_sqrt_div_ce_Q,
    output logic halt_ACT,
    output logic [31:0] i1_if_cpu_ldst_HADDR,
    output logic [2:0] i1_if_cpu_ldst_HBURST,
    output logic i1_if_cpu_ldst_HMASTLOCK,
    output logic [3:0] i1_if_cpu_ldst_HPROT,
    output logic [2:0] i1_if_cpu_ldst_HSIZE,
    output logic [1:0] i1_if_cpu_ldst_HTRANS,
    output logic [31:0] i1_if_cpu_ldst_HWDATA,
    output logic i1_if_cpu_ldst_HWRITE,
    output logic [31:0] lsu_pmp_r_pmp0_napot_mask_Q,
    output logic [31:0] lsu_pmp_r_pmp10_napot_mask_Q,
    output logic [31:0] lsu_pmp_r_pmp11_napot_mask_Q,
    output logic [31:0] lsu_pmp_r_pmp12_napot_mask_Q,
    output logic [31:0] lsu_pmp_r_pmp13_napot_mask_Q,
    output logic [31:0] lsu_pmp_r_pmp14_napot_mask_Q,
    output logic [31:0] lsu_pmp_r_pmp15_napot_mask_Q,
    output logic [31:0] lsu_pmp_r_pmp1_napot_mask_Q,
    output logic [31:0] lsu_pmp_r_pmp2_napot_mask_Q,
    output logic [31:0] lsu_pmp_r_pmp3_napot_mask_Q,
    output logic [31:0] lsu_pmp_r_pmp4_napot_mask_Q,
    output logic [31:0] lsu_pmp_r_pmp5_napot_mask_Q,
    output logic [31:0] lsu_pmp_r_pmp6_napot_mask_Q,
    output logic [31:0] lsu_pmp_r_pmp7_napot_mask_Q,
    output logic [31:0] lsu_pmp_r_pmp8_napot_mask_Q,
    output logic [31:0] lsu_pmp_r_pmp9_napot_mask_Q,
    output logic lsu_s_load_ce_Q,
    output logic lsu_s_lsu_ce_Q,
    output logic lsu_s_store_ce_Q,
    output logic [31:0] ocd_s_ocd_addr_o_Q,
    output logic ocd_s_ocd_busy_o_Q,
    output logic ocd_s_ocd_progbuf_mode_o_Q,
    output logic ocd_s_ocd_valid_o_Q,
    output logic pipe_add_sub_COMPUTE_CLEAR_D,
    output logic pipe_add_sub_COMPUTE_STALL_D,
    output logic pipe_add_sub_POSTNORM_CLEAR_D,
    output logic pipe_add_sub_POSTNORM_STALL_D,
    output logic pipe_add_sub_ROUNDING_CLEAR_D,
    output logic pipe_add_sub_ROUNDING_STALL_D,
    output logic pipe_f2i_F2I_CLEAR_D,
    output logic pipe_f2i_F2I_STALL_D,
    output logic pipe_fmul_MUL_CLEAR_D,
    output logic pipe_fmul_POSTNORM1_CLEAR_D,
    output logic pipe_fmul_POSTNORM2_CLEAR_D,
    output logic pipe_fmul_ROUNDING_CLEAR_D,
    output logic pipe_fused_ADDSUB_CLEAR_D,
    output logic pipe_fused_POSTNORM_ADDSUB_CLEAR_D,
    output logic pipe_fused_POSTNORM_MUL1_CLEAR_D,
    output logic pipe_fused_POSTNORM_MUL2_CLEAR_D,
    output logic pipe_fused_PRENORM_ADDSUB_CLEAR_D,
    output logic pipe_fused_ROUNDING_CLEAR_D,
    output logic pipe_fused_WAIT_MUL_CLEAR_D,
    output logic pipe_i2f_COMPUTE_CLEAR_D,
    output logic pipe_i2f_COMPUTE_STALL_D,
    output logic pipe_i2f_ROUNDING_CLEAR_D,
    output logic pipe_i2f_ROUNDING_STALL_D,
    output logic pipe_sqrt_div_SQRT_DIV_CLEAR_D,
    output logic pl_lsu_FIN_CLEAR_D,
    output logic pl_lsu_FIN_STALL_D,
    output logic [31:0] r_csr_dcsr_D,
    output logic r_csr_dcsr_WE,
    output logic [31:0] r_csr_dpc_D,
    output logic r_csr_dpc_WE,
    output logic [31:0] r_csr_fcsr_D,
    output logic r_csr_fcsr_WE,
    output logic [31:0] r_csr_mcause_D,
    output logic r_csr_mcause_WE,
    output logic [31:0] r_csr_mcounteren_D,
    output logic r_csr_mcounteren_WE,
    output logic [31:0] r_csr_mcountinhibit_D,
    output logic r_csr_mcountinhibit_WE,
    output logic [63:0] r_csr_mcycle_D,
    output logic r_csr_mcycle_WE,
    output logic r_csr_mdtcmen_D,
    output logic r_csr_mdtcmen_WE,
    output logic [31:0] r_csr_mepc_D,
    output logic r_csr_mepc_WE,
    output logic [31:0] r_csr_mexcause_D,
    output logic r_csr_mexcause_WE,
    output logic [31:0] r_csr_mie_D,
    output logic r_csr_mie_WE,
    output logic [63:0] r_csr_minstret_D,
    output logic r_csr_minstret_WE,
    output logic [31:0] r_csr_mip_D,
    output logic r_csr_mip_WE,
    output logic r_csr_mitcmen_D,
    output logic r_csr_mitcmen_WE,
    output logic [31:0] r_csr_mpicflag1_D,
    output logic r_csr_mpicflag1_WE,
    output logic [31:0] r_csr_mpicflag2_D,
    output logic r_csr_mpicflag2_WE,
    output logic [31:0] r_csr_mpicflag3_D,
    output logic r_csr_mpicflag3_WE,
    output logic [31:0] r_csr_mpicflag_D,
    output logic r_csr_mpicflag_WE,
    output logic [31:0] r_csr_mpicmask1_D,
    output logic r_csr_mpicmask1_WE,
    output logic [31:0] r_csr_mpicmask2_D,
    output logic r_csr_mpicmask2_WE,
    output logic [31:0] r_csr_mpicmask3_D,
    output logic r_csr_mpicmask3_WE,
    output logic [31:0] r_csr_mpicmask_D,
    output logic r_csr_mpicmask_WE,
    output logic [31:0] r_csr_mscratch_D,
    output logic r_csr_mscratch_WE,
    output logic [31:0] r_csr_mstatus_D,
    output logic r_csr_mstatus_WE,
    output logic [31:0] r_csr_mtval_D,
    output logic r_csr_mtval_WE,
    output logic [31:0] r_csr_mtvec_D,
    output logic r_csr_mtvec_WE,
    output logic [31:0] r_csr_pmpaddr0_D,
    output logic r_csr_pmpaddr0_WE,
    output logic [31:0] r_csr_pmpaddr10_D,
    output logic r_csr_pmpaddr10_WE,
    output logic [31:0] r_csr_pmpaddr11_D,
    output logic r_csr_pmpaddr11_WE,
    output logic [31:0] r_csr_pmpaddr12_D,
    output logic r_csr_pmpaddr12_WE,
    output logic [31:0] r_csr_pmpaddr13_D,
    output logic r_csr_pmpaddr13_WE,
    output logic [31:0] r_csr_pmpaddr14_D,
    output logic r_csr_pmpaddr14_WE,
    output logic [31:0] r_csr_pmpaddr15_D,
    output logic r_csr_pmpaddr15_WE,
    output logic [31:0] r_csr_pmpaddr1_D,
    output logic r_csr_pmpaddr1_WE,
    output logic [31:0] r_csr_pmpaddr2_D,
    output logic r_csr_pmpaddr2_WE,
    output logic [31:0] r_csr_pmpaddr3_D,
    output logic r_csr_pmpaddr3_WE,
    output logic [31:0] r_csr_pmpaddr4_D,
    output logic r_csr_pmpaddr4_WE,
    output logic [31:0] r_csr_pmpaddr5_D,
    output logic r_csr_pmpaddr5_WE,
    output logic [31:0] r_csr_pmpaddr6_D,
    output logic r_csr_pmpaddr6_WE,
    output logic [31:0] r_csr_pmpaddr7_D,
    output logic r_csr_pmpaddr7_WE,
    output logic [31:0] r_csr_pmpaddr8_D,
    output logic r_csr_pmpaddr8_WE,
    output logic [31:0] r_csr_pmpaddr9_D,
    output logic r_csr_pmpaddr9_WE,
    output logic [31:0] r_csr_pmpcfg0_D,
    output logic r_csr_pmpcfg0_WE,
    output logic [31:0] r_csr_pmpcfg1_D,
    output logic r_csr_pmpcfg1_WE,
    output logic [31:0] r_csr_pmpcfg2_D,
    output logic r_csr_pmpcfg2_WE,
    output logic [31:0] r_csr_pmpcfg3_D,
    output logic r_csr_pmpcfg3_WE,
    output logic [31:0] r_csr_tcontrol_D,
    output logic r_csr_tcontrol_WE,
    output logic [2:0] r_csr_tdata1_r_RA,
    output logic r_csr_tdata1_r_RE,
    output logic [31:0] r_csr_tdata1_w_D,
    output logic [2:0] r_csr_tdata1_w_WA,
    output logic r_csr_tdata1_w_WE,
    output logic [2:0] r_csr_tdata2_r_RA,
    output logic r_csr_tdata2_r_RE,
    output logic [31:0] r_csr_tdata2_w_D,
    output logic [2:0] r_csr_tdata2_w_WA,
    output logic r_csr_tdata2_w_WE,
    output logic [31:0] r_csr_tselect_D,
    output logic r_csr_tselect_WE,
    output logic [3:0] r_ex1_fu_D,
    output logic r_ex1_fu_WE,
    output logic [31:0] r_ex1_instr_addr_D,
    output logic r_ex1_instr_addr_WE,
    output logic r_ex1_is_rvc_D,
    output logic r_ex1_is_rvc_WE,
    output logic [5:0] r_ex1_rd_addr_D,
    output logic r_ex1_rd_addr_WE,
    output logic r_nmi_i_D,
    output logic r_nmi_i_WE,
    output logic [31:0] r_nmi_mtval_D,
    output logic r_nmi_mtval_WE,
    output logic r_nmi_source_D,
    output logic r_nmi_source_WE,
    output logic [1:0] r_prv_D,
    output logic r_prv_WE,
    output logic r_wfi_ce_D,
    output logic r_wfi_ce_WE,
    output logic [4:0] rf_fr_r1_RA,
    output logic rf_fr_r1_RE,
    output logic [4:0] rf_fr_r2_RA,
    output logic rf_fr_r2_RE,
    output logic [4:0] rf_fr_r3_RA,
    output logic rf_fr_r3_RE,
    output logic [31:0] rf_fr_w_D,
    output logic [4:0] rf_fr_w_WA,
    output logic rf_fr_w_WE,
    output logic [4:0] rf_gpr_r1_RA,
    output logic rf_gpr_r1_RE,
    output logic [4:0] rf_gpr_r2_RA,
    output logic rf_gpr_r2_RE,
    output logic [31:0] rf_gpr_w0_D,
    output logic [4:0] rf_gpr_w0_WA,
    output logic rf_gpr_w0_WE,
    output logic [31:0] rf_gpr_w1_D,
    output logic [4:0] rf_gpr_w1_WA,
    output logic rf_gpr_w1_WE,
    output logic s_dm_progbuf_done_D,
    output logic s_dm_progbuf_exc_D,
    output logic s_ex1_clear_D,
    output logic s_ex1_stall_D,
    output logic s_ex_bp_flush_D,
    output logic s_ex_bp_flush_line_D,
    output logic s_ex_bp_restart_D,
    output logic s_ex_branch_bht_update_D,
    output logic s_ex_branch_btb_update_D,
    output logic [31:0] s_ex_branch_instr_addr_D,
    output logic s_ex_branch_is_rvc_D,
    output logic s_ex_branch_miss_D,
    output logic [31:0] s_ex_branch_offset_D,
    output logic s_ex_branch_taken_D,
    output logic [31:0] s_ex_branch_target_addr_D,
    output logic s_ex_clear_D,
    output logic s_ex_fence_valid_D,
    output logic s_ex_fpu_busy_D,
    output logic [5:0] s_ex_p0_addr_D,
    output logic s_ex_p0_we_D,
    output logic [5:0] s_ex_p1_addr_D,
    output logic s_ex_p1_we_D,
    output logic s_ex_progbuf_mode_D,
    output logic [5:0] s_ex_rd_addr_D,
    output logic [31:0] s_ex_rd_data_D,
    output logic s_ex_rd_we_D,
    output logic s_ex_return_link_D,
    output logic s_ex_return_update_D,
    output logic s_ex_stall_D,
    output logic s_flush_D,
    output logic s_fpu_ce_D,
    output logic [31:0] s_fpu_dst_regs_D,
    output logic s_hart_halted_D,
    output logic s_perf_branch_miss_D,
    output logic s_perf_csr_flush_D,
    output logic s_perf_div_stall_D,
    output logic s_perf_exc_flush_D,
    output logic s_perf_fpu_stall_D,
    output logic s_perf_int_flush_D,
    output logic s_perf_lsu_stall_D,
    output logic [11:0] s_perf_waddr_D,
    output logic [31:0] s_perf_wdata_D,
    output logic [1:0] s_perf_we_D,
    output logic s_progbuf_mode_active_D,
    output logic [5:0] s_rd0_addr_D,
    output logic [31:0] s_rd0_data_D,
    output logic s_rd0_we_D,
    output logic s_rd0_write_D,
    output logic [5:0] s_rd1_addr_D,
    output logic [31:0] s_rd1_data_D,
    output logic s_rd1_we_D,
    output logic s_rd1_write_D,
    output logic s_wfi_prevent_fetch_D
);
    // additional declarations:
    logic ex_alu_compute_ACT_wire;
    logic [7:0] ex_alu_s_op_i_D_wire;
    logic [31:0] ex_alu_s_s1_data_i_D_wire;
    logic [31:0] ex_alu_s_s2_data_i_D_wire;
    logic [31:0] alu_s_rd_data_o_Q_wire;
    logic alu_s_take_branch_o_Q_wire;
    logic ex_b_unit_compute_ACT_wire;
    logic [7:0] ex_b_unit_s_op_i_D_wire;
    logic [31:0] ex_b_unit_s_s1_data_i_D_wire;
    logic [31:0] ex_b_unit_s_s2_data_i_D_wire;
    logic [31:0] b_unit_s_rd_data_o_Q_wire;
    logic ex_bru_compute_ACT_wire;
    logic [31:0] ex_bru_s_bp_addr_i_D_wire;
    logic ex_bru_s_bp_taken_i_D_wire;
    logic [31:0] ex_bru_s_imm_i_D_wire;
    logic [31:0] ex_bru_s_instr_addr_i_D_wire;
    logic ex_bru_s_is_rvc_i_D_wire;
    logic [7:0] ex_bru_s_op_i_D_wire;
    logic [31:0] ex_bru_s_rs1_data_i_D_wire;
    logic ex_bru_s_take_branch_i_D_wire;
    logic bru_s_branch_bht_update_o_Q_wire;
    logic bru_s_branch_btb_update_o_Q_wire;
    logic bru_s_branch_miss_o_Q_wire;
    logic bru_s_branch_taken_o_Q_wire;
    logic [31:0] bru_s_branch_target_addr_o_Q_wire;
    logic [31:0] bru_s_rd_data_o_Q_wire;
    logic bru_s_rd_we_o_Q_wire;
    logic [11:0] ex_crf_s_csr_addr_i_D_wire;
    logic ex_crf_s_csr_re_i_D_wire;
    logic ex_crf_s_csr_valid_i_D_wire;
    logic [31:0] ex_crf_s_csr_wdata_i_D_wire;
    logic ex_crf_s_csr_we_i_D_wire;
    logic [127:0] ex_crf_s_eip_i_D_wire;
    logic [1:0] ex_crf_s_exc_extra_i_D_wire;
    logic [31:0] ex_crf_s_exc_tval_i_D_wire;
    logic [4:0] ex_crf_s_exc_type_i_D_wire;
    logic ex_crf_s_exc_valid_i_D_wire;
    logic [4:0] ex_crf_s_fflags_i_D_wire;
    logic ex_crf_s_fs_context_change_i_D_wire;
    logic [3:0] ex_crf_s_fu1_i_D_wire;
    logic ex_crf_s_instr_1_valid_i_D_wire;
    logic [31:0] ex_crf_s_instr_addr_i_D_wire;
    logic ex_crf_s_instr_valid_excint_i_D_wire;
    logic ex_crf_s_instr_valid_i_D_wire;
    logic [31:0] ex_crf_s_int_addr_i_D_wire;
    logic ex_crf_s_int_safe_to_take_i_D_wire;
    logic ex_crf_s_nmi_i_D_wire;
    logic [31:0] ex_crf_s_nmi_mtval_i_D_wire;
    logic ex_crf_s_nmi_source_i_D_wire;
    logic ex_crf_s_ocd_busy_i_D_wire;
    logic [31:0] ex_crf_s_ocd_dcsr_i_D_wire;
    logic ex_crf_s_ocd_debug_mode_req_i_D_wire;
    logic [31:0] ex_crf_s_ocd_dpc_i_D_wire;
    logic ex_crf_s_ocd_flush_i_D_wire;
    logic ex_crf_s_ocd_progbuf_mode_i_D_wire;
    logic ex_crf_s_ocd_user_mode_req_i_D_wire;
    logic [7:0] ex_crf_s_op_i_D_wire;
    logic ex_crf_s_sip_i_D_wire;
    logic ex_crf_s_tip_i_D_wire;
    logic ex_crf_s_wfi_delay_i_D_wire;
    logic ex_crf_s_write_fflags_i_D_wire;
    logic [11:0] crf_lsu_pmp_s_csr_waddr_i_D_wire;
    logic [31:0] crf_lsu_pmp_s_csr_wdata_i_D_wire;
    logic crf_lsu_pmp_s_csr_we_i_D_wire;
    logic crf_r_fce_wfi_valid_Q_wire;
    logic [31:0] crf_s_csr_addr_o_Q_wire;
    logic crf_s_csr_flush_o_Q_wire;
    logic crf_s_csr_valid_o_Q_wire;
    logic crf_s_exc_flush_o_Q_wire;
    logic [4:0] crf_s_exc_type_o_Q_wire;
    logic crf_s_exc_valid_o_Q_wire;
    logic crf_s_flush_o_Q_wire;
    logic crf_s_instr_1_valid_i_Q_wire;
    logic crf_s_int_flush_o_Q_wire;
    logic crf_s_int_stall_o_Q_wire;
    logic [31:0] crf_s_intexc_trap_addr_Q_wire;
    logic crf_s_intexc_trap_valid_Q_wire;
    logic [11:0] crf_s_perf_waddr_o_Q_wire;
    logic [31:0] crf_s_perf_wdata_o_Q_wire;
    logic [1:0] crf_s_perf_we_o_Q_wire;
    logic [31:0] crf_s_rdata_o_Q_wire;
    logic crf_s_take_nmi_o_Q_wire;
    logic crf_s_wfi_o_Q_wire;
    logic [11:0] ex_csr_s_csr_addr_i_D_wire;
    logic [5:0] ex_csr_s_csr_s1_addr_i_D_wire;
    logic [1:0] ex_csr_s_csr_s1_source_i_D_wire;
    logic [31:0] ex_csr_s_csr_wdata_i_D_wire;
    logic [7:0] ex_csr_s_op_i_D_wire;
    logic [11:0] csr_s_csr_addr_o_Q_wire;
    logic csr_s_csr_rd_we_o_Q_wire;
    logic csr_s_csr_re_o_Q_wire;
    logic csr_s_csr_valid_o_Q_wire;
    logic [31:0] csr_s_csr_wdata_o_Q_wire;
    logic csr_s_csr_we_o_Q_wire;
    logic ex_div_div_compute_ACT_wire;
    logic ex_div_s_div_ce_i_D_wire;
    logic ex_div_s_flush_i_D_wire;
    logic [7:0] ex_div_s_op_i_D_wire;
    logic [31:0] ex_div_s_s1_data_i_D_wire;
    logic [31:0] ex_div_s_s2_data_i_D_wire;
    logic div_s_busy_o_Q_wire;
    logic [31:0] div_s_rd_data_o_Q_wire;
    logic div_s_rd_valid_o_Q_wire;
    logic ex_fpu_s_ack_i_D_wire;
    logic [4:0] ex_fpu_s_exc_type_i_D_wire;
    logic ex_fpu_s_exc_valid_i_D_wire;
    logic ex_fpu_s_flush_i_D_wire;
    logic [2:0] ex_fpu_s_frm_i_D_wire;
    logic [31:0] ex_fpu_s_instr_addr_i_D_wire;
    logic [31:0] ex_fpu_s_instr_i_D_wire;
    logic [5:0] ex_fpu_s_op_i_D_wire;
    logic [5:0] ex_fpu_s_rd_addr_i_D_wire;
    logic [2:0] ex_fpu_s_rm_i_D_wire;
    logic [5:0] ex_fpu_s_s1_addr_i_D_wire;
    logic [31:0] ex_fpu_s_s1_data_i_D_wire;
    logic [5:0] ex_fpu_s_s2_addr_i_D_wire;
    logic [31:0] ex_fpu_s_s2_data_i_D_wire;
    logic [5:0] ex_fpu_s_s3_addr_i_D_wire;
    logic [31:0] ex_fpu_s_s3_data_i_D_wire;
    logic ex_fpu_s_valid_i_D_wire;
    logic fpu_s_busy_o_Q_wire;
    logic [31:0] fpu_s_exc_instr_addr_o_Q_wire;
    logic [31:0] fpu_s_exc_tval_o_Q_wire;
    logic [4:0] fpu_s_exc_type_o_Q_wire;
    logic fpu_s_exc_valid_o_Q_wire;
    logic [4:0] fpu_s_flags_o_Q_wire;
    logic [5:0] fpu_s_rd_addr_o_Q_wire;
    logic [31:0] fpu_s_rd_data_o_Q_wire;
    logic [31:0] fpu_s_rdx_valid_o_Q_wire;
    logic fpu_s_ready_o_Q_wire;
    logic fpu_s_valid_o_Q_wire;
    logic [31:0] ex_ira_s_ex0_branch_target_i_D_wire;
    logic [31:0] ex_ira_s_ex0_csr_addr_i_D_wire;
    logic [31:0] ex_ira_s_ex0_instr_addr_i_D_wire;
    logic [31:0] ex_ira_s_ex0_intexc_addr_i_D_wire;
    logic ex_ira_s_ex0_is_branch_i_D_wire;
    logic ex_ira_s_ex0_is_csr_i_D_wire;
    logic ex_ira_s_ex0_is_intexc_i_D_wire;
    logic ex_ira_s_ex0_is_rvc_i_D_wire;
    logic ex_ira_s_ex0_retired_i_D_wire;
    logic [31:0] ex_ira_s_ex1_instr_addr_i_D_wire;
    logic ex_ira_s_ex1_is_rvc_i_D_wire;
    logic ex_ira_s_ex1_retired_i_D_wire;
    logic [31:0] ex_ira_s_ocd_addr_i_D_wire;
    logic ex_ira_s_ocd_stop_count_i_D_wire;
    logic ex_ira_s_ocd_valid_i_D_wire;
    logic [31:0] ira_r_return_address_Q_wire;
    logic ira_s_ex0_retired_i_Q_wire;
    logic ira_s_ex1_retired_i_Q_wire;
    logic [31:0] ira_s_int_addr_o_Q_wire;
    logic [31:0] ex_lsu_s_addr_i_D_wire;
    logic ex_lsu_s_clear_i_D_wire;
    logic ex_lsu_s_ocd_mmode_i_D_wire;
    logic [7:0] ex_lsu_s_op_i_D_wire;
    logic [5:0] ex_lsu_s_rd_addr_i_D_wire;
    logic [31:0] ex_lsu_s_syscall_addr_i_D_wire;
    logic [31:0] ex_lsu_s_wdata_i_D_wire;
    logic lsu_s_fin_busy_o_Q_wire;
    logic [1:0] lsu_s_fin_exc_extra_o_Q_wire;
    logic [31:0] lsu_s_fin_exc_tval_o_Q_wire;
    logic [4:0] lsu_s_fin_exc_type_o_Q_wire;
    logic lsu_s_fin_exc_valid_o_Q_wire;
    logic [7:0] lsu_s_fin_op_o_Q_wire;
    logic [5:0] lsu_s_fin_rd_addr_o_Q_wire;
    logic [31:0] lsu_s_fin_rd_data_o_Q_wire;
    logic lsu_s_fin_rd_valid_o_Q_wire;
    logic lsu_s_fin_rd_we_o_Q_wire;
    logic lsu_s_is_load_Q_wire;
    logic [1:0] lsu_s_req_exc_extra_o_Q_wire;
    logic [31:0] lsu_s_req_exc_tval_o_Q_wire;
    logic [4:0] lsu_s_req_exc_type_o_Q_wire;
    logic lsu_s_req_exc_valid_o_Q_wire;
    logic lsu_s_waited_transfer_o_Q_wire;
    logic ex_mul_compute_ACT_wire;
    logic [7:0] ex_mul_s_op_i_D_wire;
    logic [31:0] ex_mul_s_s1_data_i_D_wire;
    logic [31:0] ex_mul_s_s2_data_i_D_wire;
    logic [31:0] mul_s_rd_data_o_Q_wire;
    logic ex_ocd_s_dm_active_i_D_wire;
    logic ex_ocd_s_dm_halt_i_D_wire;
    logic ex_ocd_s_dm_progbuf_en_i_D_wire;
    logic [4:0] ex_ocd_s_exc_type_i_D_wire;
    logic ex_ocd_s_exc_valid_i_D_wire;
    logic [31:0] ex_ocd_s_instr_addr_i_D_wire;
    logic ex_ocd_s_instr_commit_i_D_wire;
    logic ex_ocd_s_instr_valid_i_D_wire;
    logic ocd_s_dm_progbuf_done_o_Q_wire;
    logic ocd_s_dm_progbuf_exc_o_Q_wire;
    logic ocd_s_hart_halted_o_Q_wire;
    logic [31:0] ocd_s_ocd_addr_o_Q_wire;
    logic ocd_s_ocd_busy_o_Q_wire;
    logic [31:0] ocd_s_ocd_dcsr_o_Q_wire;
    logic ocd_s_ocd_debug_mode_req_o_Q_wire;
    logic [31:0] ocd_s_ocd_dpc_o_Q_wire;
    logic ocd_s_ocd_flush_o_Q_wire;
    logic ocd_s_ocd_progbuf_mode_o_Q_wire;
    logic ocd_s_ocd_step_commited_o_Q_wire;
    logic ocd_s_ocd_step_mode_o_Q_wire;
    logic ocd_s_ocd_user_mod_req_o_Q_wire;
    logic ocd_s_ocd_valid_o_Q_wire;

    // child instances inside CodAL module:
    // CodAL module instance:
    codix_berkelium_ca_core_execute_stage_alu_t alu (
        .compute_ACT(ex_alu_compute_ACT_wire),
        .s_op_i_D(ex_alu_s_op_i_D_wire),
        .s_s1_data_i_D(ex_alu_s_s1_data_i_D_wire),
        .s_s2_data_i_D(ex_alu_s_s2_data_i_D_wire),
        .s_rd_data_o_Q(alu_s_rd_data_o_Q_wire),
        .s_take_branch_o_Q(alu_s_take_branch_o_Q_wire)
    );

    // CodAL module instance:
    codix_berkelium_ca_core_execute_stage_b_unit_t b_unit (
        .compute_ACT(ex_b_unit_compute_ACT_wire),
        .s_op_i_D(ex_b_unit_s_op_i_D_wire),
        .s_s1_data_i_D(ex_b_unit_s_s1_data_i_D_wire),
        .s_s2_data_i_D(ex_b_unit_s_s2_data_i_D_wire),
        .s_rd_data_o_Q(b_unit_s_rd_data_o_Q_wire)
    );

    // CodAL module instance:
    codix_berkelium_ca_core_execute_stage_bru_t bru (
        .compute_ACT(ex_bru_compute_ACT_wire),
        .s_bp_addr_i_D(ex_bru_s_bp_addr_i_D_wire),
        .s_bp_taken_i_D(ex_bru_s_bp_taken_i_D_wire),
        .s_imm_i_D(ex_bru_s_imm_i_D_wire),
        .s_instr_addr_i_D(ex_bru_s_instr_addr_i_D_wire),
        .s_is_rvc_i_D(ex_bru_s_is_rvc_i_D_wire),
        .s_op_i_D(ex_bru_s_op_i_D_wire),
        .s_rs1_data_i_D(ex_bru_s_rs1_data_i_D_wire),
        .s_take_branch_i_D(ex_bru_s_take_branch_i_D_wire),
        .s_branch_bht_update_o_Q(bru_s_branch_bht_update_o_Q_wire),
        .s_branch_btb_update_o_Q(bru_s_branch_btb_update_o_Q_wire),
        .s_branch_miss_o_Q(bru_s_branch_miss_o_Q_wire),
        .s_branch_taken_o_Q(bru_s_branch_taken_o_Q_wire),
        .s_branch_target_addr_o_Q(bru_s_branch_target_addr_o_Q_wire),
        .s_is_jump_o_Q(bru_s_is_jump_o_Q),
        .s_rd_data_o_Q(bru_s_rd_data_o_Q_wire),
        .s_rd_we_o_Q(bru_s_rd_we_o_Q_wire)
    );
    assign bru_s_branch_bht_update_o_Q = bru_s_branch_bht_update_o_Q_wire;
    assign bru_s_rd_data_o_Q = bru_s_rd_data_o_Q_wire;

    // CodAL module instance:
    codix_berkelium_ca_core_execute_stage_crf_t #(
        .nmi_handler_p(nmi_handler_p),
        .itcm_size_p(itcm_size_p),
        .itcm_baddr_p(itcm_baddr_p),
        .dtcm_size_p(dtcm_size_p),
        .dtcm_baddr_p(dtcm_baddr_p),
        .cache_base_p(cache_base_p),
        .hart_id_p(hart_id_p)
    ) crf (
        .r_wfi_ce_ICLK(r_wfi_ce_ICLK),
        .RST(RST),
        .p_dtcm_en_Q(p_dtcm_en_Q),
        .p_itcm_en_Q(p_itcm_en_Q),
        .perf_r_mhpmcounter10_Q(perf_r_mhpmcounter10_Q),
        .perf_r_mhpmcounter12_Q(perf_r_mhpmcounter12_Q),
        .perf_r_mhpmcounter13_Q(perf_r_mhpmcounter13_Q),
        .perf_r_mhpmcounter14_Q(perf_r_mhpmcounter14_Q),
        .perf_r_mhpmcounter15_Q(perf_r_mhpmcounter15_Q),
        .perf_r_mhpmcounter3_Q(perf_r_mhpmcounter3_Q),
        .perf_r_mhpmcounter4_Q(perf_r_mhpmcounter4_Q),
        .perf_r_mhpmcounter5_Q(perf_r_mhpmcounter5_Q),
        .perf_r_mhpmcounter6_Q(perf_r_mhpmcounter6_Q),
        .perf_r_mhpmcounter9_Q(perf_r_mhpmcounter9_Q),
        .r_csr_dcsr_Q(r_csr_dcsr_Q),
        .r_csr_dpc_Q(r_csr_dpc_Q),
        .r_csr_fcsr_Q(r_csr_fcsr_Q),
        .r_csr_mcause_Q(r_csr_mcause_Q),
        .r_csr_mcounteren_Q(r_csr_mcounteren_Q),
        .r_csr_mcountinhibit_Q(r_csr_mcountinhibit_Q),
        .r_csr_mcycle_Q(r_csr_mcycle_Q),
        .r_csr_mdtcmen_Q(r_csr_mdtcmen_Q),
        .r_csr_mepc_Q(r_csr_mepc_Q),
        .r_csr_mexcause_Q(r_csr_mexcause_Q),
        .r_csr_mie_Q(r_csr_mie_Q),
        .r_csr_minstret_Q(r_csr_minstret_Q),
        .r_csr_mip_Q(r_csr_mip_Q),
        .r_csr_mitcmen_Q(r_csr_mitcmen_Q),
        .r_csr_mpicflag1_Q(r_csr_mpicflag1_Q),
        .r_csr_mpicflag2_Q(r_csr_mpicflag2_Q),
        .r_csr_mpicflag3_Q(r_csr_mpicflag3_Q),
        .r_csr_mpicflag_Q(r_csr_mpicflag_Q),
        .r_csr_mpicmask1_Q(r_csr_mpicmask1_Q),
        .r_csr_mpicmask2_Q(r_csr_mpicmask2_Q),
        .r_csr_mpicmask3_Q(r_csr_mpicmask3_Q),
        .r_csr_mpicmask_Q(r_csr_mpicmask_Q),
        .r_csr_mscratch_Q(r_csr_mscratch_Q),
        .r_csr_mstatus_Q(r_csr_mstatus_Q),
        .r_csr_mtval_Q(r_csr_mtval_Q),
        .r_csr_mtvec_Q(r_csr_mtvec_Q),
        .r_csr_pmpaddr0_Q(r_csr_pmpaddr0_Q),
        .r_csr_pmpaddr10_Q(r_csr_pmpaddr10_Q),
        .r_csr_pmpaddr11_Q(r_csr_pmpaddr11_Q),
        .r_csr_pmpaddr12_Q(r_csr_pmpaddr12_Q),
        .r_csr_pmpaddr13_Q(r_csr_pmpaddr13_Q),
        .r_csr_pmpaddr14_Q(r_csr_pmpaddr14_Q),
        .r_csr_pmpaddr15_Q(r_csr_pmpaddr15_Q),
        .r_csr_pmpaddr1_Q(r_csr_pmpaddr1_Q),
        .r_csr_pmpaddr2_Q(r_csr_pmpaddr2_Q),
        .r_csr_pmpaddr3_Q(r_csr_pmpaddr3_Q),
        .r_csr_pmpaddr4_Q(r_csr_pmpaddr4_Q),
        .r_csr_pmpaddr5_Q(r_csr_pmpaddr5_Q),
        .r_csr_pmpaddr6_Q(r_csr_pmpaddr6_Q),
        .r_csr_pmpaddr7_Q(r_csr_pmpaddr7_Q),
        .r_csr_pmpaddr8_Q(r_csr_pmpaddr8_Q),
        .r_csr_pmpaddr9_Q(r_csr_pmpaddr9_Q),
        .r_csr_pmpcfg0_Q(r_csr_pmpcfg0_Q),
        .r_csr_pmpcfg1_Q(r_csr_pmpcfg1_Q),
        .r_csr_pmpcfg2_Q(r_csr_pmpcfg2_Q),
        .r_csr_pmpcfg3_Q(r_csr_pmpcfg3_Q),
        .r_csr_tcontrol_Q(r_csr_tcontrol_Q),
        .r_csr_tdata1_r_Q(r_csr_tdata1_r_Q),
        .r_csr_tdata2_r_Q(r_csr_tdata2_r_Q),
        .r_csr_tselect_Q(r_csr_tselect_Q),
        .r_prv_Q(r_prv_Q),
        .r_reset_init_Q(r_reset_init_Q),
        .r_wfi_ce_Q(r_wfi_ce_Q),
        .s_csr_addr_i_D(ex_crf_s_csr_addr_i_D_wire),
        .s_csr_re_i_D(ex_crf_s_csr_re_i_D_wire),
        .s_csr_valid_i_D(ex_crf_s_csr_valid_i_D_wire),
        .s_csr_wdata_i_D(ex_crf_s_csr_wdata_i_D_wire),
        .s_csr_we_i_D(ex_crf_s_csr_we_i_D_wire),
        .s_eip_i_D(ex_crf_s_eip_i_D_wire),
        .s_exc_extra_i_D(ex_crf_s_exc_extra_i_D_wire),
        .s_exc_tval_i_D(ex_crf_s_exc_tval_i_D_wire),
        .s_exc_type_i_D(ex_crf_s_exc_type_i_D_wire),
        .s_exc_valid_i_D(ex_crf_s_exc_valid_i_D_wire),
        .s_fflags_i_D(ex_crf_s_fflags_i_D_wire),
        .s_fs_context_change_i_D(ex_crf_s_fs_context_change_i_D_wire),
        .s_fu1_i_D(ex_crf_s_fu1_i_D_wire),
        .s_instr_1_valid_i_D(ex_crf_s_instr_1_valid_i_D_wire),
        .s_instr_addr_i_D(ex_crf_s_instr_addr_i_D_wire),
        .s_instr_valid_excint_i_D(ex_crf_s_instr_valid_excint_i_D_wire),
        .s_instr_valid_i_D(ex_crf_s_instr_valid_i_D_wire),
        .s_int_addr_i_D(ex_crf_s_int_addr_i_D_wire),
        .s_int_safe_to_take_i_D(ex_crf_s_int_safe_to_take_i_D_wire),
        .s_nmi_i_D(ex_crf_s_nmi_i_D_wire),
        .s_nmi_mtval_i_D(ex_crf_s_nmi_mtval_i_D_wire),
        .s_nmi_source_i_D(ex_crf_s_nmi_source_i_D_wire),
        .s_ocd_busy_i_D(ex_crf_s_ocd_busy_i_D_wire),
        .s_ocd_dcsr_i_D(ex_crf_s_ocd_dcsr_i_D_wire),
        .s_ocd_debug_mode_req_i_D(ex_crf_s_ocd_debug_mode_req_i_D_wire),
        .s_ocd_dpc_i_D(ex_crf_s_ocd_dpc_i_D_wire),
        .s_ocd_flush_i_D(ex_crf_s_ocd_flush_i_D_wire),
        .s_ocd_progbuf_mode_i_D(ex_crf_s_ocd_progbuf_mode_i_D_wire),
        .s_ocd_user_mode_req_i_D(ex_crf_s_ocd_user_mode_req_i_D_wire),
        .s_op_i_D(ex_crf_s_op_i_D_wire),
        .s_sip_i_D(ex_crf_s_sip_i_D_wire),
        .s_tip_i_D(ex_crf_s_tip_i_D_wire),
        .s_wfi_delay_i_D(ex_crf_s_wfi_delay_i_D_wire),
        .s_write_fflags_i_D(ex_crf_s_write_fflags_i_D_wire),
        .lsu_pmp_s_csr_waddr_i_D(crf_lsu_pmp_s_csr_waddr_i_D_wire),
        .lsu_pmp_s_csr_wdata_i_D(crf_lsu_pmp_s_csr_wdata_i_D_wire),
        .lsu_pmp_s_csr_we_i_D(crf_lsu_pmp_s_csr_we_i_D_wire),
        .r_csr_dcsr_D(r_csr_dcsr_D),
        .r_csr_dcsr_WE(r_csr_dcsr_WE),
        .r_csr_dpc_D(r_csr_dpc_D),
        .r_csr_dpc_WE(r_csr_dpc_WE),
        .r_csr_fcsr_D(r_csr_fcsr_D),
        .r_csr_fcsr_WE(r_csr_fcsr_WE),
        .r_csr_mcause_D(r_csr_mcause_D),
        .r_csr_mcause_WE(r_csr_mcause_WE),
        .r_csr_mcounteren_D(r_csr_mcounteren_D),
        .r_csr_mcounteren_WE(r_csr_mcounteren_WE),
        .r_csr_mcountinhibit_D(r_csr_mcountinhibit_D),
        .r_csr_mcountinhibit_WE(r_csr_mcountinhibit_WE),
        .r_csr_mcycle_D(r_csr_mcycle_D),
        .r_csr_mcycle_WE(r_csr_mcycle_WE),
        .r_csr_mdtcmen_D(r_csr_mdtcmen_D),
        .r_csr_mdtcmen_WE(r_csr_mdtcmen_WE),
        .r_csr_mepc_D(r_csr_mepc_D),
        .r_csr_mepc_WE(r_csr_mepc_WE),
        .r_csr_mexcause_D(r_csr_mexcause_D),
        .r_csr_mexcause_WE(r_csr_mexcause_WE),
        .r_csr_mie_D(r_csr_mie_D),
        .r_csr_mie_WE(r_csr_mie_WE),
        .r_csr_minstret_D(r_csr_minstret_D),
        .r_csr_minstret_WE(r_csr_minstret_WE),
        .r_csr_mip_D(r_csr_mip_D),
        .r_csr_mip_WE(r_csr_mip_WE),
        .r_csr_mitcmen_D(r_csr_mitcmen_D),
        .r_csr_mitcmen_WE(r_csr_mitcmen_WE),
        .r_csr_mpicflag1_D(r_csr_mpicflag1_D),
        .r_csr_mpicflag1_WE(r_csr_mpicflag1_WE),
        .r_csr_mpicflag2_D(r_csr_mpicflag2_D),
        .r_csr_mpicflag2_WE(r_csr_mpicflag2_WE),
        .r_csr_mpicflag3_D(r_csr_mpicflag3_D),
        .r_csr_mpicflag3_WE(r_csr_mpicflag3_WE),
        .r_csr_mpicflag_D(r_csr_mpicflag_D),
        .r_csr_mpicflag_WE(r_csr_mpicflag_WE),
        .r_csr_mpicmask1_D(r_csr_mpicmask1_D),
        .r_csr_mpicmask1_WE(r_csr_mpicmask1_WE),
        .r_csr_mpicmask2_D(r_csr_mpicmask2_D),
        .r_csr_mpicmask2_WE(r_csr_mpicmask2_WE),
        .r_csr_mpicmask3_D(r_csr_mpicmask3_D),
        .r_csr_mpicmask3_WE(r_csr_mpicmask3_WE),
        .r_csr_mpicmask_D(r_csr_mpicmask_D),
        .r_csr_mpicmask_WE(r_csr_mpicmask_WE),
        .r_csr_mscratch_D(r_csr_mscratch_D),
        .r_csr_mscratch_WE(r_csr_mscratch_WE),
        .r_csr_mstatus_D(r_csr_mstatus_D),
        .r_csr_mstatus_WE(r_csr_mstatus_WE),
        .r_csr_mtval_D(r_csr_mtval_D),
        .r_csr_mtval_WE(r_csr_mtval_WE),
        .r_csr_mtvec_D(r_csr_mtvec_D),
        .r_csr_mtvec_WE(r_csr_mtvec_WE),
        .r_csr_tcontrol_D(r_csr_tcontrol_D),
        .r_csr_tcontrol_WE(r_csr_tcontrol_WE),
        .r_csr_tdata1_r_RA(r_csr_tdata1_r_RA),
        .r_csr_tdata1_r_RE(r_csr_tdata1_r_RE),
        .r_csr_tdata1_w_D(r_csr_tdata1_w_D),
        .r_csr_tdata1_w_WA(r_csr_tdata1_w_WA),
        .r_csr_tdata1_w_WE(r_csr_tdata1_w_WE),
        .r_csr_tdata2_r_RA(r_csr_tdata2_r_RA),
        .r_csr_tdata2_r_RE(r_csr_tdata2_r_RE),
        .r_csr_tdata2_w_D(r_csr_tdata2_w_D),
        .r_csr_tdata2_w_WA(r_csr_tdata2_w_WA),
        .r_csr_tdata2_w_WE(r_csr_tdata2_w_WE),
        .r_csr_tselect_D(r_csr_tselect_D),
        .r_csr_tselect_WE(r_csr_tselect_WE),
        .r_fce_wfi_valid_Q(crf_r_fce_wfi_valid_Q_wire),
        .r_prv_D(r_prv_D),
        .r_prv_WE(r_prv_WE),
        .s_csr_addr_o_Q(crf_s_csr_addr_o_Q_wire),
        .s_csr_flush_o_Q(crf_s_csr_flush_o_Q_wire),
        .s_csr_valid_o_Q(crf_s_csr_valid_o_Q_wire),
        .s_exc_flush_o_Q(crf_s_exc_flush_o_Q_wire),
        .s_exc_type_o_Q(crf_s_exc_type_o_Q_wire),
        .s_exc_valid_o_Q(crf_s_exc_valid_o_Q_wire),
        .s_flush_o_Q(crf_s_flush_o_Q_wire),
        .s_hpm_inhibit_o_Q(crf_s_hpm_inhibit_o_Q),
        .s_instr_1_valid_i_Q(crf_s_instr_1_valid_i_Q_wire),
        .s_int_flush_o_Q(crf_s_int_flush_o_Q_wire),
        .s_int_stall_o_Q(crf_s_int_stall_o_Q_wire),
        .s_intexc_trap_addr_Q(crf_s_intexc_trap_addr_Q_wire),
        .s_intexc_trap_valid_Q(crf_s_intexc_trap_valid_Q_wire),
        .s_perf_inhibit_o_Q(crf_s_perf_inhibit_o_Q),
        .s_perf_waddr_o_Q(crf_s_perf_waddr_o_Q_wire),
        .s_perf_wdata_o_Q(crf_s_perf_wdata_o_Q_wire),
        .s_perf_we_o_Q(crf_s_perf_we_o_Q_wire),
        .s_rdata_o_Q(crf_s_rdata_o_Q_wire),
        .s_take_nmi_o_Q(crf_s_take_nmi_o_Q_wire),
        .s_trap_addr_o_Q(crf_s_trap_addr_o_Q),
        .s_trap_valid_o_Q(crf_s_trap_valid_o_Q),
        .s_wfi_o_Q(crf_s_wfi_o_Q_wire)
    );
    assign crf_s_csr_addr_o_Q = crf_s_csr_addr_o_Q_wire;
    assign crf_s_csr_valid_o_Q = crf_s_csr_valid_o_Q_wire;

    // CodAL module instance:
    codix_berkelium_ca_core_execute_stage_csr_t csr (
        .s_csr_addr_i_D(ex_csr_s_csr_addr_i_D_wire),
        .s_csr_s1_addr_i_D(ex_csr_s_csr_s1_addr_i_D_wire),
        .s_csr_s1_source_i_D(ex_csr_s_csr_s1_source_i_D_wire),
        .s_csr_wdata_i_D(ex_csr_s_csr_wdata_i_D_wire),
        .s_op_i_D(ex_csr_s_op_i_D_wire),
        .s_csr_addr_o_Q(csr_s_csr_addr_o_Q_wire),
        .s_csr_rd_we_o_Q(csr_s_csr_rd_we_o_Q_wire),
        .s_csr_re_o_Q(csr_s_csr_re_o_Q_wire),
        .s_csr_valid_o_Q(csr_s_csr_valid_o_Q_wire),
        .s_csr_wdata_o_Q(csr_s_csr_wdata_o_Q_wire),
        .s_csr_we_o_Q(csr_s_csr_we_o_Q_wire)
    );

    // CodAL module instance:
    codix_berkelium_ca_core_execute_stage_div_t div (
        .execute_stage_div_s_div_ce_i_ICLK(execute_stage_div_s_div_ce_i_ICLK),
        .RST(RST),
        .div_compute_ACT(ex_div_div_compute_ACT_wire),
        .s_div_ce_i_D(ex_div_s_div_ce_i_D_wire),
        .s_flush_i_D(ex_div_s_flush_i_D_wire),
        .s_op_i_D(ex_div_s_op_i_D_wire),
        .s_s1_data_i_D(ex_div_s_s1_data_i_D_wire),
        .s_s2_data_i_D(ex_div_s_s2_data_i_D_wire),
        .s_busy_o_Q(div_s_busy_o_Q_wire),
        .s_div_ce_i_Q(div_s_div_ce_i_Q),
        .s_rd_data_o_Q(div_s_rd_data_o_Q_wire),
        .s_rd_valid_o_Q(div_s_rd_valid_o_Q_wire)
    );

    // CodAL module instance:
    codix_berkelium_ca_core_execute_stage_fpu_t fpu (
        .execute_stage_fpu_add_sub_s_add_sub_ce_ICLK(execute_stage_fpu_add_sub_s_add_sub_ce_ICLK),
        .execute_stage_fpu_float2int_s_f2i_ce_ICLK(execute_stage_fpu_float2int_s_f2i_ce_ICLK),
        .execute_stage_fpu_fmul_s_fmul_ce_ICLK(execute_stage_fpu_fmul_s_fmul_ce_ICLK),
        .execute_stage_fpu_fused_s_fused_ce_ICLK(execute_stage_fpu_fused_s_fused_ce_ICLK),
        .execute_stage_fpu_int2float_s_i2f_ce_ICLK(execute_stage_fpu_int2float_s_i2f_ce_ICLK),
        .execute_stage_fpu_sqrt_div_s_sqrt_div_ce_ICLK(execute_stage_fpu_sqrt_div_s_sqrt_div_ce_ICLK),
        .s_fpu_ce_ICLK(s_fpu_ce_ICLK),
        .RST(RST),
        .control_fpu_CONTROL_CLEAR_Q(control_fpu_CONTROL_CLEAR_Q),
        .control_fpu_CONTROL_STALL_Q(control_fpu_CONTROL_STALL_Q),
        .control_fpu_ROB_CLEAR_Q(control_fpu_ROB_CLEAR_Q),
        .pipe_add_sub_COMPUTE_CLEAR_Q(pipe_add_sub_COMPUTE_CLEAR_Q),
        .pipe_add_sub_COMPUTE_STALL_Q(pipe_add_sub_COMPUTE_STALL_Q),
        .pipe_add_sub_POSTNORM_CLEAR_Q(pipe_add_sub_POSTNORM_CLEAR_Q),
        .pipe_add_sub_POSTNORM_STALL_Q(pipe_add_sub_POSTNORM_STALL_Q),
        .pipe_add_sub_ROUNDING_CLEAR_Q(pipe_add_sub_ROUNDING_CLEAR_Q),
        .pipe_add_sub_ROUNDING_STALL_Q(pipe_add_sub_ROUNDING_STALL_Q),
        .pipe_f2i_F2I_CLEAR_Q(pipe_f2i_F2I_CLEAR_Q),
        .pipe_f2i_F2I_STALL_Q(pipe_f2i_F2I_STALL_Q),
        .pipe_fmul_MUL_CLEAR_Q(pipe_fmul_MUL_CLEAR_Q),
        .pipe_fmul_POSTNORM1_CLEAR_Q(pipe_fmul_POSTNORM1_CLEAR_Q),
        .pipe_fmul_POSTNORM2_CLEAR_Q(pipe_fmul_POSTNORM2_CLEAR_Q),
        .pipe_fmul_ROUNDING_CLEAR_Q(pipe_fmul_ROUNDING_CLEAR_Q),
        .pipe_fused_ADDSUB_CLEAR_Q(pipe_fused_ADDSUB_CLEAR_Q),
        .pipe_fused_POSTNORM_ADDSUB_CLEAR_Q(pipe_fused_POSTNORM_ADDSUB_CLEAR_Q),
        .pipe_fused_POSTNORM_MUL1_CLEAR_Q(pipe_fused_POSTNORM_MUL1_CLEAR_Q),
        .pipe_fused_POSTNORM_MUL2_CLEAR_Q(pipe_fused_POSTNORM_MUL2_CLEAR_Q),
        .pipe_fused_PRENORM_ADDSUB_CLEAR_Q(pipe_fused_PRENORM_ADDSUB_CLEAR_Q),
        .pipe_fused_ROUNDING_CLEAR_Q(pipe_fused_ROUNDING_CLEAR_Q),
        .pipe_fused_WAIT_MUL_CLEAR_Q(pipe_fused_WAIT_MUL_CLEAR_Q),
        .pipe_i2f_COMPUTE_CLEAR_Q(pipe_i2f_COMPUTE_CLEAR_Q),
        .pipe_i2f_COMPUTE_STALL_Q(pipe_i2f_COMPUTE_STALL_Q),
        .pipe_i2f_ROUNDING_CLEAR_Q(pipe_i2f_ROUNDING_CLEAR_Q),
        .pipe_i2f_ROUNDING_STALL_Q(pipe_i2f_ROUNDING_STALL_Q),
        .pipe_sqrt_div_SQRT_DIV_CLEAR_Q(pipe_sqrt_div_SQRT_DIV_CLEAR_Q),
        .s_ack_i_D(ex_fpu_s_ack_i_D_wire),
        .s_exc_type_i_D(ex_fpu_s_exc_type_i_D_wire),
        .s_exc_valid_i_D(ex_fpu_s_exc_valid_i_D_wire),
        .s_flush_i_D(ex_fpu_s_flush_i_D_wire),
        .s_frm_i_D(ex_fpu_s_frm_i_D_wire),
        .s_instr_addr_i_D(ex_fpu_s_instr_addr_i_D_wire),
        .s_instr_i_D(ex_fpu_s_instr_i_D_wire),
        .s_op_i_D(ex_fpu_s_op_i_D_wire),
        .s_rd_addr_i_D(ex_fpu_s_rd_addr_i_D_wire),
        .s_rm_i_D(ex_fpu_s_rm_i_D_wire),
        .s_s1_addr_i_D(ex_fpu_s_s1_addr_i_D_wire),
        .s_s1_data_i_D(ex_fpu_s_s1_data_i_D_wire),
        .s_s2_addr_i_D(ex_fpu_s_s2_addr_i_D_wire),
        .s_s2_data_i_D(ex_fpu_s_s2_data_i_D_wire),
        .s_s3_addr_i_D(ex_fpu_s_s3_addr_i_D_wire),
        .s_s3_data_i_D(ex_fpu_s_s3_data_i_D_wire),
        .s_valid_i_D(ex_fpu_s_valid_i_D_wire),
        .add_sub_s_add_sub_ce_Q(fpu_add_sub_s_add_sub_ce_Q),
        .control_fpu_CONTROL_CLEAR_D(control_fpu_CONTROL_CLEAR_D),
        .control_fpu_CONTROL_STALL_D(control_fpu_CONTROL_STALL_D),
        .control_fpu_ROB_CLEAR_D(control_fpu_ROB_CLEAR_D),
        .float2int_s_f2i_ce_Q(fpu_float2int_s_f2i_ce_Q),
        .fmul_s_fmul_ce_Q(fpu_fmul_s_fmul_ce_Q),
        .fused_s_fused_ce_Q(fpu_fused_s_fused_ce_Q),
        .int2float_s_i2f_ce_Q(fpu_int2float_s_i2f_ce_Q),
        .pipe_add_sub_COMPUTE_CLEAR_D(pipe_add_sub_COMPUTE_CLEAR_D),
        .pipe_add_sub_COMPUTE_STALL_D(pipe_add_sub_COMPUTE_STALL_D),
        .pipe_add_sub_POSTNORM_CLEAR_D(pipe_add_sub_POSTNORM_CLEAR_D),
        .pipe_add_sub_POSTNORM_STALL_D(pipe_add_sub_POSTNORM_STALL_D),
        .pipe_add_sub_ROUNDING_CLEAR_D(pipe_add_sub_ROUNDING_CLEAR_D),
        .pipe_add_sub_ROUNDING_STALL_D(pipe_add_sub_ROUNDING_STALL_D),
        .pipe_f2i_F2I_CLEAR_D(pipe_f2i_F2I_CLEAR_D),
        .pipe_f2i_F2I_STALL_D(pipe_f2i_F2I_STALL_D),
        .pipe_fmul_MUL_CLEAR_D(pipe_fmul_MUL_CLEAR_D),
        .pipe_fmul_POSTNORM1_CLEAR_D(pipe_fmul_POSTNORM1_CLEAR_D),
        .pipe_fmul_POSTNORM2_CLEAR_D(pipe_fmul_POSTNORM2_CLEAR_D),
        .pipe_fmul_ROUNDING_CLEAR_D(pipe_fmul_ROUNDING_CLEAR_D),
        .pipe_fused_ADDSUB_CLEAR_D(pipe_fused_ADDSUB_CLEAR_D),
        .pipe_fused_POSTNORM_ADDSUB_CLEAR_D(pipe_fused_POSTNORM_ADDSUB_CLEAR_D),
        .pipe_fused_POSTNORM_MUL1_CLEAR_D(pipe_fused_POSTNORM_MUL1_CLEAR_D),
        .pipe_fused_POSTNORM_MUL2_CLEAR_D(pipe_fused_POSTNORM_MUL2_CLEAR_D),
        .pipe_fused_PRENORM_ADDSUB_CLEAR_D(pipe_fused_PRENORM_ADDSUB_CLEAR_D),
        .pipe_fused_ROUNDING_CLEAR_D(pipe_fused_ROUNDING_CLEAR_D),
        .pipe_fused_WAIT_MUL_CLEAR_D(pipe_fused_WAIT_MUL_CLEAR_D),
        .pipe_i2f_COMPUTE_CLEAR_D(pipe_i2f_COMPUTE_CLEAR_D),
        .pipe_i2f_COMPUTE_STALL_D(pipe_i2f_COMPUTE_STALL_D),
        .pipe_i2f_ROUNDING_CLEAR_D(pipe_i2f_ROUNDING_CLEAR_D),
        .pipe_i2f_ROUNDING_STALL_D(pipe_i2f_ROUNDING_STALL_D),
        .pipe_sqrt_div_SQRT_DIV_CLEAR_D(pipe_sqrt_div_SQRT_DIV_CLEAR_D),
        .s_busy_o_Q(fpu_s_busy_o_Q_wire),
        .s_exc_instr_addr_o_Q(fpu_s_exc_instr_addr_o_Q_wire),
        .s_exc_tval_o_Q(fpu_s_exc_tval_o_Q_wire),
        .s_exc_type_o_Q(fpu_s_exc_type_o_Q_wire),
        .s_exc_valid_o_Q(fpu_s_exc_valid_o_Q_wire),
        .s_flags_o_Q(fpu_s_flags_o_Q_wire),
        .s_fpu_ce_D(s_fpu_ce_D),
        .s_rd_addr_o_Q(fpu_s_rd_addr_o_Q_wire),
        .s_rd_data_o_Q(fpu_s_rd_data_o_Q_wire),
        .s_rdx_valid_o_Q(fpu_s_rdx_valid_o_Q_wire),
        .s_ready_o_Q(fpu_s_ready_o_Q_wire),
        .s_valid_o_Q(fpu_s_valid_o_Q_wire),
        .sqrt_div_s_sqrt_div_ce_Q(fpu_sqrt_div_s_sqrt_div_ce_Q)
    );

    // CodAL module instance:
    codix_berkelium_ca_core_execute_stage_ira_t ira (
        .r_wfi_ce_ICLK(r_wfi_ce_ICLK),
        .RST(RST),
        .r_return_address_D(ira_r_return_address_D),
        .r_return_address_WE(ira_r_return_address_WE),
        .s_ex0_branch_target_i_D(ex_ira_s_ex0_branch_target_i_D_wire),
        .s_ex0_csr_addr_i_D(ex_ira_s_ex0_csr_addr_i_D_wire),
        .s_ex0_instr_addr_i_D(ex_ira_s_ex0_instr_addr_i_D_wire),
        .s_ex0_intexc_addr_i_D(ex_ira_s_ex0_intexc_addr_i_D_wire),
        .s_ex0_is_branch_i_D(ex_ira_s_ex0_is_branch_i_D_wire),
        .s_ex0_is_csr_i_D(ex_ira_s_ex0_is_csr_i_D_wire),
        .s_ex0_is_intexc_i_D(ex_ira_s_ex0_is_intexc_i_D_wire),
        .s_ex0_is_rvc_i_D(ex_ira_s_ex0_is_rvc_i_D_wire),
        .s_ex0_retired_i_D(ex_ira_s_ex0_retired_i_D_wire),
        .s_ex1_instr_addr_i_D(ex_ira_s_ex1_instr_addr_i_D_wire),
        .s_ex1_is_rvc_i_D(ex_ira_s_ex1_is_rvc_i_D_wire),
        .s_ex1_retired_i_D(ex_ira_s_ex1_retired_i_D_wire),
        .s_ocd_addr_i_D(ex_ira_s_ocd_addr_i_D_wire),
        .s_ocd_stop_count_i_D(ex_ira_s_ocd_stop_count_i_D_wire),
        .s_ocd_valid_i_D(ex_ira_s_ocd_valid_i_D_wire),
        .r_return_address_Q(ira_r_return_address_Q_wire),
        .s_ex0_retired_i_Q(ira_s_ex0_retired_i_Q_wire),
        .s_ex1_retired_i_Q(ira_s_ex1_retired_i_Q_wire),
        .s_int_addr_o_Q(ira_s_int_addr_o_Q_wire)
    );

    // CodAL module instance:
    codix_berkelium_ca_core_execute_stage_lsu_t #(
        .pma_base0_p(pma_base0_p),
        .pma_mask0_p(pma_mask0_p),
        .pma_enable_p(pma_enable_p),
        .pma_base1_p(pma_base1_p),
        .pma_mask1_p(pma_mask1_p),
        .pma_base2_p(pma_base2_p),
        .pma_mask2_p(pma_mask2_p),
        .pma_base3_p(pma_base3_p),
        .pma_mask3_p(pma_mask3_p),
        .pma_base4_p(pma_base4_p),
        .pma_mask4_p(pma_mask4_p),
        .pma_base5_p(pma_base5_p),
        .pma_mask5_p(pma_mask5_p),
        .pma_base6_p(pma_base6_p),
        .pma_mask6_p(pma_mask6_p),
        .pma_base7_p(pma_base7_p),
        .pma_mask7_p(pma_mask7_p),
        .pma_base8_p(pma_base8_p),
        .pma_mask8_p(pma_mask8_p),
        .pma_base9_p(pma_base9_p),
        .pma_mask9_p(pma_mask9_p),
        .pma_base10_p(pma_base10_p),
        .pma_mask10_p(pma_mask10_p),
        .pma_base11_p(pma_base11_p),
        .pma_mask11_p(pma_mask11_p),
        .pma_base12_p(pma_base12_p),
        .pma_mask12_p(pma_mask12_p),
        .pma_base13_p(pma_base13_p),
        .pma_mask13_p(pma_mask13_p),
        .pma_base14_p(pma_base14_p),
        .pma_mask14_p(pma_mask14_p),
        .pma_base15_p(pma_base15_p),
        .pma_mask15_p(pma_mask15_p),
        .pma_cfg15_p(pma_cfg15_p),
        .pma_cfg14_p(pma_cfg14_p),
        .pma_cfg13_p(pma_cfg13_p),
        .pma_cfg12_p(pma_cfg12_p),
        .pma_cfg11_p(pma_cfg11_p),
        .pma_cfg10_p(pma_cfg10_p),
        .pma_cfg9_p(pma_cfg9_p),
        .pma_cfg8_p(pma_cfg8_p),
        .pma_cfg7_p(pma_cfg7_p),
        .pma_cfg6_p(pma_cfg6_p),
        .pma_cfg5_p(pma_cfg5_p),
        .pma_cfg4_p(pma_cfg4_p),
        .pma_cfg3_p(pma_cfg3_p),
        .pma_cfg2_p(pma_cfg2_p),
        .pma_cfg1_p(pma_cfg1_p),
        .pma_cfg0_p(pma_cfg0_p),
        .cache_base_p(cache_base_p)
    ) lsu (
        .execute_stage_lsu_s_load_ce_ICLK(execute_stage_lsu_s_load_ce_ICLK),
        .execute_stage_lsu_s_lsu_ce_ICLK(execute_stage_lsu_s_lsu_ce_ICLK),
        .execute_stage_lsu_s_store_ce_ICLK(execute_stage_lsu_s_store_ce_ICLK),
        .r_wfi_ce_ICLK(r_wfi_ce_ICLK),
        .RST(RST),
        .i1_if_cpu_ldst_HRDATA(i1_if_cpu_ldst_HRDATA),
        .i1_if_cpu_ldst_HREADY(i1_if_cpu_ldst_HREADY),
        .i1_if_cpu_ldst_HRESP(i1_if_cpu_ldst_HRESP),
        .pl_lsu_FIN_CLEAR_Q(pl_lsu_FIN_CLEAR_Q),
        .pl_lsu_FIN_STALL_Q(pl_lsu_FIN_STALL_Q),
        .pmp_s_csr_waddr_i_D(crf_lsu_pmp_s_csr_waddr_i_D_wire),
        .pmp_s_csr_wdata_i_D(crf_lsu_pmp_s_csr_wdata_i_D_wire),
        .pmp_s_csr_we_i_D(crf_lsu_pmp_s_csr_we_i_D_wire),
        .r_csr_mstatus_Q(r_csr_mstatus_Q[17:11]),
        .r_csr_pmpaddr0_Q(r_csr_pmpaddr0_Q),
        .r_csr_pmpaddr10_Q(r_csr_pmpaddr10_Q),
        .r_csr_pmpaddr11_Q(r_csr_pmpaddr11_Q),
        .r_csr_pmpaddr12_Q(r_csr_pmpaddr12_Q),
        .r_csr_pmpaddr13_Q(r_csr_pmpaddr13_Q),
        .r_csr_pmpaddr14_Q(r_csr_pmpaddr14_Q),
        .r_csr_pmpaddr15_Q(r_csr_pmpaddr15_Q),
        .r_csr_pmpaddr1_Q(r_csr_pmpaddr1_Q),
        .r_csr_pmpaddr2_Q(r_csr_pmpaddr2_Q),
        .r_csr_pmpaddr3_Q(r_csr_pmpaddr3_Q),
        .r_csr_pmpaddr4_Q(r_csr_pmpaddr4_Q),
        .r_csr_pmpaddr5_Q(r_csr_pmpaddr5_Q),
        .r_csr_pmpaddr6_Q(r_csr_pmpaddr6_Q),
        .r_csr_pmpaddr7_Q(r_csr_pmpaddr7_Q),
        .r_csr_pmpaddr8_Q(r_csr_pmpaddr8_Q),
        .r_csr_pmpaddr9_Q(r_csr_pmpaddr9_Q),
        .r_csr_pmpcfg0_Q(r_csr_pmpcfg0_Q),
        .r_csr_pmpcfg1_Q(r_csr_pmpcfg1_Q),
        .r_csr_pmpcfg2_Q(r_csr_pmpcfg2_Q),
        .r_csr_pmpcfg3_Q(r_csr_pmpcfg3_Q),
        .r_prv_Q(r_prv_Q),
        .s_addr_i_D(ex_lsu_s_addr_i_D_wire),
        .s_clear_i_D(ex_lsu_s_clear_i_D_wire),
        .s_ocd_mmode_i_D(ex_lsu_s_ocd_mmode_i_D_wire),
        .s_op_i_D(ex_lsu_s_op_i_D_wire),
        .s_rd_addr_i_D(ex_lsu_s_rd_addr_i_D_wire),
        .s_syscall_addr_i_D(ex_lsu_s_syscall_addr_i_D_wire),
        .s_wdata_i_D(ex_lsu_s_wdata_i_D_wire),
        .halt_ACT(halt_ACT),
        .i1_if_cpu_ldst_HADDR(i1_if_cpu_ldst_HADDR),
        .i1_if_cpu_ldst_HBURST(i1_if_cpu_ldst_HBURST),
        .i1_if_cpu_ldst_HMASTLOCK(i1_if_cpu_ldst_HMASTLOCK),
        .i1_if_cpu_ldst_HPROT(i1_if_cpu_ldst_HPROT),
        .i1_if_cpu_ldst_HSIZE(i1_if_cpu_ldst_HSIZE),
        .i1_if_cpu_ldst_HTRANS(i1_if_cpu_ldst_HTRANS),
        .i1_if_cpu_ldst_HWDATA(i1_if_cpu_ldst_HWDATA),
        .i1_if_cpu_ldst_HWRITE(i1_if_cpu_ldst_HWRITE),
        .pl_lsu_FIN_CLEAR_D(pl_lsu_FIN_CLEAR_D),
        .pl_lsu_FIN_STALL_D(pl_lsu_FIN_STALL_D),
        .pmp_r_pmp0_napot_mask_Q(lsu_pmp_r_pmp0_napot_mask_Q),
        .pmp_r_pmp10_napot_mask_Q(lsu_pmp_r_pmp10_napot_mask_Q),
        .pmp_r_pmp11_napot_mask_Q(lsu_pmp_r_pmp11_napot_mask_Q),
        .pmp_r_pmp12_napot_mask_Q(lsu_pmp_r_pmp12_napot_mask_Q),
        .pmp_r_pmp13_napot_mask_Q(lsu_pmp_r_pmp13_napot_mask_Q),
        .pmp_r_pmp14_napot_mask_Q(lsu_pmp_r_pmp14_napot_mask_Q),
        .pmp_r_pmp15_napot_mask_Q(lsu_pmp_r_pmp15_napot_mask_Q),
        .pmp_r_pmp1_napot_mask_Q(lsu_pmp_r_pmp1_napot_mask_Q),
        .pmp_r_pmp2_napot_mask_Q(lsu_pmp_r_pmp2_napot_mask_Q),
        .pmp_r_pmp3_napot_mask_Q(lsu_pmp_r_pmp3_napot_mask_Q),
        .pmp_r_pmp4_napot_mask_Q(lsu_pmp_r_pmp4_napot_mask_Q),
        .pmp_r_pmp5_napot_mask_Q(lsu_pmp_r_pmp5_napot_mask_Q),
        .pmp_r_pmp6_napot_mask_Q(lsu_pmp_r_pmp6_napot_mask_Q),
        .pmp_r_pmp7_napot_mask_Q(lsu_pmp_r_pmp7_napot_mask_Q),
        .pmp_r_pmp8_napot_mask_Q(lsu_pmp_r_pmp8_napot_mask_Q),
        .pmp_r_pmp9_napot_mask_Q(lsu_pmp_r_pmp9_napot_mask_Q),
        .r_csr_pmpaddr0_D(r_csr_pmpaddr0_D),
        .r_csr_pmpaddr0_WE(r_csr_pmpaddr0_WE),
        .r_csr_pmpaddr10_D(r_csr_pmpaddr10_D),
        .r_csr_pmpaddr10_WE(r_csr_pmpaddr10_WE),
        .r_csr_pmpaddr11_D(r_csr_pmpaddr11_D),
        .r_csr_pmpaddr11_WE(r_csr_pmpaddr11_WE),
        .r_csr_pmpaddr12_D(r_csr_pmpaddr12_D),
        .r_csr_pmpaddr12_WE(r_csr_pmpaddr12_WE),
        .r_csr_pmpaddr13_D(r_csr_pmpaddr13_D),
        .r_csr_pmpaddr13_WE(r_csr_pmpaddr13_WE),
        .r_csr_pmpaddr14_D(r_csr_pmpaddr14_D),
        .r_csr_pmpaddr14_WE(r_csr_pmpaddr14_WE),
        .r_csr_pmpaddr15_D(r_csr_pmpaddr15_D),
        .r_csr_pmpaddr15_WE(r_csr_pmpaddr15_WE),
        .r_csr_pmpaddr1_D(r_csr_pmpaddr1_D),
        .r_csr_pmpaddr1_WE(r_csr_pmpaddr1_WE),
        .r_csr_pmpaddr2_D(r_csr_pmpaddr2_D),
        .r_csr_pmpaddr2_WE(r_csr_pmpaddr2_WE),
        .r_csr_pmpaddr3_D(r_csr_pmpaddr3_D),
        .r_csr_pmpaddr3_WE(r_csr_pmpaddr3_WE),
        .r_csr_pmpaddr4_D(r_csr_pmpaddr4_D),
        .r_csr_pmpaddr4_WE(r_csr_pmpaddr4_WE),
        .r_csr_pmpaddr5_D(r_csr_pmpaddr5_D),
        .r_csr_pmpaddr5_WE(r_csr_pmpaddr5_WE),
        .r_csr_pmpaddr6_D(r_csr_pmpaddr6_D),
        .r_csr_pmpaddr6_WE(r_csr_pmpaddr6_WE),
        .r_csr_pmpaddr7_D(r_csr_pmpaddr7_D),
        .r_csr_pmpaddr7_WE(r_csr_pmpaddr7_WE),
        .r_csr_pmpaddr8_D(r_csr_pmpaddr8_D),
        .r_csr_pmpaddr8_WE(r_csr_pmpaddr8_WE),
        .r_csr_pmpaddr9_D(r_csr_pmpaddr9_D),
        .r_csr_pmpaddr9_WE(r_csr_pmpaddr9_WE),
        .r_csr_pmpcfg0_D(r_csr_pmpcfg0_D),
        .r_csr_pmpcfg0_WE(r_csr_pmpcfg0_WE),
        .r_csr_pmpcfg1_D(r_csr_pmpcfg1_D),
        .r_csr_pmpcfg1_WE(r_csr_pmpcfg1_WE),
        .r_csr_pmpcfg2_D(r_csr_pmpcfg2_D),
        .r_csr_pmpcfg2_WE(r_csr_pmpcfg2_WE),
        .r_csr_pmpcfg3_D(r_csr_pmpcfg3_D),
        .r_csr_pmpcfg3_WE(r_csr_pmpcfg3_WE),
        .s_fin_busy_o_Q(lsu_s_fin_busy_o_Q_wire),
        .s_fin_exc_extra_o_Q(lsu_s_fin_exc_extra_o_Q_wire),
        .s_fin_exc_tval_o_Q(lsu_s_fin_exc_tval_o_Q_wire),
        .s_fin_exc_type_o_Q(lsu_s_fin_exc_type_o_Q_wire),
        .s_fin_exc_valid_o_Q(lsu_s_fin_exc_valid_o_Q_wire),
        .s_fin_op_o_Q(lsu_s_fin_op_o_Q_wire),
        .s_fin_rd_addr_o_Q(lsu_s_fin_rd_addr_o_Q_wire),
        .s_fin_rd_data_o_Q(lsu_s_fin_rd_data_o_Q_wire),
        .s_fin_rd_valid_o_Q(lsu_s_fin_rd_valid_o_Q_wire),
        .s_fin_rd_we_o_Q(lsu_s_fin_rd_we_o_Q_wire),
        .s_is_load_Q(lsu_s_is_load_Q_wire),
        .s_load_ce_Q(lsu_s_load_ce_Q),
        .s_lsu_ce_Q(lsu_s_lsu_ce_Q),
        .s_req_exc_extra_o_Q(lsu_s_req_exc_extra_o_Q_wire),
        .s_req_exc_tval_o_Q(lsu_s_req_exc_tval_o_Q_wire),
        .s_req_exc_type_o_Q(lsu_s_req_exc_type_o_Q_wire),
        .s_req_exc_valid_o_Q(lsu_s_req_exc_valid_o_Q_wire),
        .s_store_ce_Q(lsu_s_store_ce_Q),
        .s_waited_transfer_o_Q(lsu_s_waited_transfer_o_Q_wire)
    );

    // CodAL module instance:
    codix_berkelium_ca_core_execute_stage_mul_t mul (
        .compute_ACT(ex_mul_compute_ACT_wire),
        .s_op_i_D(ex_mul_s_op_i_D_wire),
        .s_s1_data_i_D(ex_mul_s_s1_data_i_D_wire),
        .s_s2_data_i_D(ex_mul_s_s2_data_i_D_wire),
        .s_rd_data_o_Q(mul_s_rd_data_o_Q_wire)
    );

    // CodAL module instance:
    codix_berkelium_ca_core_execute_stage_ocd_t #(
        .progbuf_base_p(progbuf_base_p)
    ) ocd (
        .r_wfi_ce_ICLK(r_wfi_ce_ICLK),
        .RST(RST),
        .r_csr_dcsr_Q(r_csr_dcsr_Q[31:2]),
        .r_csr_dpc_Q(r_csr_dpc_Q),
        .r_prv_Q(r_prv_Q),
        .s_dm_active_i_D(ex_ocd_s_dm_active_i_D_wire),
        .s_dm_halt_i_D(ex_ocd_s_dm_halt_i_D_wire),
        .s_dm_halt_Q(s_dm_halt_Q),
        .s_dm_progbuf_en_i_D(ex_ocd_s_dm_progbuf_en_i_D_wire),
        .s_exc_type_i_D(ex_ocd_s_exc_type_i_D_wire),
        .s_exc_valid_i_D(ex_ocd_s_exc_valid_i_D_wire),
        .s_instr_addr_i_D(ex_ocd_s_instr_addr_i_D_wire),
        .s_instr_commit_i_D(ex_ocd_s_instr_commit_i_D_wire),
        .s_instr_valid_i_D(ex_ocd_s_instr_valid_i_D_wire),
        .s_dm_progbuf_done_o_Q(ocd_s_dm_progbuf_done_o_Q_wire),
        .s_dm_progbuf_exc_o_Q(ocd_s_dm_progbuf_exc_o_Q_wire),
        .s_hart_halted_o_Q(ocd_s_hart_halted_o_Q_wire),
        .s_ocd_addr_o_Q(ocd_s_ocd_addr_o_Q_wire),
        .s_ocd_busy_o_Q(ocd_s_ocd_busy_o_Q_wire),
        .s_ocd_dcsr_o_Q(ocd_s_ocd_dcsr_o_Q_wire),
        .s_ocd_debug_mode_req_o_Q(ocd_s_ocd_debug_mode_req_o_Q_wire),
        .s_ocd_dpc_o_Q(ocd_s_ocd_dpc_o_Q_wire),
        .s_ocd_flush_o_Q(ocd_s_ocd_flush_o_Q_wire),
        .s_ocd_progbuf_mode_o_Q(ocd_s_ocd_progbuf_mode_o_Q_wire),
        .s_ocd_step_commited_o_Q(ocd_s_ocd_step_commited_o_Q_wire),
        .s_ocd_step_mode_o_Q(ocd_s_ocd_step_mode_o_Q_wire),
        .s_ocd_user_mod_req_o_Q(ocd_s_ocd_user_mod_req_o_Q_wire),
        .s_ocd_valid_o_Q(ocd_s_ocd_valid_o_Q_wire)
    );
    assign ocd_s_ocd_addr_o_Q = ocd_s_ocd_addr_o_Q_wire;
    assign ocd_s_ocd_busy_o_Q = ocd_s_ocd_busy_o_Q_wire;
    assign ocd_s_ocd_progbuf_mode_o_Q = ocd_s_ocd_progbuf_mode_o_Q_wire;
    assign ocd_s_ocd_valid_o_Q = ocd_s_ocd_valid_o_Q_wire;

    // functional unit instance:
    codix_berkelium_ca_core_execute_stage_ex_t ex (
        .alu_s_rd_data_o_Q(alu_s_rd_data_o_Q_wire),
        .alu_s_take_branch_o_Q(alu_s_take_branch_o_Q_wire),
        .b_unit_s_rd_data_o_Q(b_unit_s_rd_data_o_Q_wire),
        .bru_s_branch_bht_update_o_Q(bru_s_branch_bht_update_o_Q_wire),
        .bru_s_branch_btb_update_o_Q(bru_s_branch_btb_update_o_Q_wire),
        .bru_s_branch_miss_o_Q(bru_s_branch_miss_o_Q_wire),
        .bru_s_branch_taken_o_Q(bru_s_branch_taken_o_Q_wire),
        .bru_s_branch_target_addr_o_Q(bru_s_branch_target_addr_o_Q_wire),
        .bru_s_rd_data_o_Q(bru_s_rd_data_o_Q_wire),
        .bru_s_rd_we_o_Q(bru_s_rd_we_o_Q_wire),
        .crf_r_fce_wfi_valid_Q(crf_r_fce_wfi_valid_Q_wire),
        .crf_s_csr_addr_o_Q(crf_s_csr_addr_o_Q_wire),
        .crf_s_csr_flush_o_Q(crf_s_csr_flush_o_Q_wire),
        .crf_s_csr_valid_o_Q(crf_s_csr_valid_o_Q_wire),
        .crf_s_exc_flush_o_Q(crf_s_exc_flush_o_Q_wire),
        .crf_s_exc_type_o_Q(crf_s_exc_type_o_Q_wire),
        .crf_s_exc_valid_o_Q(crf_s_exc_valid_o_Q_wire),
        .crf_s_flush_o_Q(crf_s_flush_o_Q_wire),
        .crf_s_instr_1_valid_i_Q(crf_s_instr_1_valid_i_Q_wire),
        .crf_s_int_flush_o_Q(crf_s_int_flush_o_Q_wire),
        .crf_s_int_stall_o_Q(crf_s_int_stall_o_Q_wire),
        .crf_s_intexc_trap_addr_Q(crf_s_intexc_trap_addr_Q_wire),
        .crf_s_intexc_trap_valid_Q(crf_s_intexc_trap_valid_Q_wire),
        .crf_s_perf_waddr_o_Q(crf_s_perf_waddr_o_Q_wire),
        .crf_s_perf_wdata_o_Q(crf_s_perf_wdata_o_Q_wire),
        .crf_s_perf_we_o_Q(crf_s_perf_we_o_Q_wire),
        .crf_s_rdata_o_Q(crf_s_rdata_o_Q_wire),
        .crf_s_take_nmi_o_Q(crf_s_take_nmi_o_Q_wire),
        .crf_s_wfi_o_Q(crf_s_wfi_o_Q_wire),
        .csr_s_csr_addr_o_Q(csr_s_csr_addr_o_Q_wire),
        .csr_s_csr_rd_we_o_Q(csr_s_csr_rd_we_o_Q_wire),
        .csr_s_csr_re_o_Q(csr_s_csr_re_o_Q_wire),
        .csr_s_csr_valid_o_Q(csr_s_csr_valid_o_Q_wire),
        .csr_s_csr_wdata_o_Q(csr_s_csr_wdata_o_Q_wire),
        .csr_s_csr_we_o_Q(csr_s_csr_we_o_Q_wire),
        .div_s_busy_o_Q(div_s_busy_o_Q_wire),
        .div_s_rd_data_o_Q(div_s_rd_data_o_Q_wire),
        .div_s_rd_valid_o_Q(div_s_rd_valid_o_Q_wire),
        .fetch_stage_ifu_s_bus_busy_o_Q(fetch_stage_ifu_s_bus_busy_o_Q),
        .fpu_s_busy_o_Q(fpu_s_busy_o_Q_wire),
        .fpu_s_exc_instr_addr_o_Q(fpu_s_exc_instr_addr_o_Q_wire),
        .fpu_s_exc_tval_o_Q(fpu_s_exc_tval_o_Q_wire),
        .fpu_s_exc_type_o_Q(fpu_s_exc_type_o_Q_wire),
        .fpu_s_exc_valid_o_Q(fpu_s_exc_valid_o_Q_wire),
        .fpu_s_flags_o_Q(fpu_s_flags_o_Q_wire),
        .fpu_s_rd_addr_o_Q(fpu_s_rd_addr_o_Q_wire),
        .fpu_s_rd_data_o_Q(fpu_s_rd_data_o_Q_wire),
        .fpu_s_rdx_valid_o_Q(fpu_s_rdx_valid_o_Q_wire),
        .fpu_s_ready_o_Q(fpu_s_ready_o_Q_wire),
        .fpu_s_valid_o_Q(fpu_s_valid_o_Q_wire),
        .ira_r_return_address_Q(ira_r_return_address_Q_wire),
        .ira_s_ex0_retired_i_Q(ira_s_ex0_retired_i_Q_wire),
        .ira_s_ex1_retired_i_Q(ira_s_ex1_retired_i_Q_wire),
        .ira_s_int_addr_o_Q(ira_s_int_addr_o_Q_wire),
        .lsu_s_fin_busy_o_Q(lsu_s_fin_busy_o_Q_wire),
        .lsu_s_fin_exc_extra_o_Q(lsu_s_fin_exc_extra_o_Q_wire),
        .lsu_s_fin_exc_tval_o_Q(lsu_s_fin_exc_tval_o_Q_wire),
        .lsu_s_fin_exc_type_o_Q(lsu_s_fin_exc_type_o_Q_wire),
        .lsu_s_fin_exc_valid_o_Q(lsu_s_fin_exc_valid_o_Q_wire),
        .lsu_s_fin_op_o_Q(lsu_s_fin_op_o_Q_wire),
        .lsu_s_fin_rd_addr_o_Q(lsu_s_fin_rd_addr_o_Q_wire),
        .lsu_s_fin_rd_data_o_Q(lsu_s_fin_rd_data_o_Q_wire),
        .lsu_s_fin_rd_valid_o_Q(lsu_s_fin_rd_valid_o_Q_wire),
        .lsu_s_fin_rd_we_o_Q(lsu_s_fin_rd_we_o_Q_wire),
        .lsu_s_is_load_Q(lsu_s_is_load_Q_wire),
        .lsu_s_req_exc_extra_o_Q(lsu_s_req_exc_extra_o_Q_wire),
        .lsu_s_req_exc_tval_o_Q(lsu_s_req_exc_tval_o_Q_wire),
        .lsu_s_req_exc_type_o_Q(lsu_s_req_exc_type_o_Q_wire),
        .lsu_s_req_exc_valid_o_Q(lsu_s_req_exc_valid_o_Q_wire),
        .lsu_s_waited_transfer_o_Q(lsu_s_waited_transfer_o_Q_wire),
        .mul_s_rd_data_o_Q(mul_s_rd_data_o_Q_wire),
        .ocd_s_dm_progbuf_done_o_Q(ocd_s_dm_progbuf_done_o_Q_wire),
        .ocd_s_dm_progbuf_exc_o_Q(ocd_s_dm_progbuf_exc_o_Q_wire),
        .ocd_s_hart_halted_o_Q(ocd_s_hart_halted_o_Q_wire),
        .ocd_s_ocd_addr_o_Q(ocd_s_ocd_addr_o_Q_wire),
        .ocd_s_ocd_busy_o_Q(ocd_s_ocd_busy_o_Q_wire),
        .ocd_s_ocd_dcsr_o_Q(ocd_s_ocd_dcsr_o_Q_wire),
        .ocd_s_ocd_debug_mode_req_o_Q(ocd_s_ocd_debug_mode_req_o_Q_wire),
        .ocd_s_ocd_dpc_o_Q(ocd_s_ocd_dpc_o_Q_wire),
        .ocd_s_ocd_flush_o_Q(ocd_s_ocd_flush_o_Q_wire),
        .ocd_s_ocd_progbuf_mode_o_Q(ocd_s_ocd_progbuf_mode_o_Q_wire),
        .ocd_s_ocd_step_commited_o_Q(ocd_s_ocd_step_commited_o_Q_wire),
        .ocd_s_ocd_step_mode_o_Q(ocd_s_ocd_step_mode_o_Q_wire),
        .ocd_s_ocd_user_mod_req_o_Q(ocd_s_ocd_user_mod_req_o_Q_wire),
        .ocd_s_ocd_valid_o_Q(ocd_s_ocd_valid_o_Q_wire),
        .p_int_Q(p_int_Q),
        .p_msip_Q(p_msip_Q),
        .p_mtip_Q(p_mtip_Q),
        .p_nmi_mtval_Q(p_nmi_mtval_Q),
        .p_nmi_Q(p_nmi_Q),
        .r_csr_dcsr_Q(r_csr_dcsr_Q[11:2]),
        .r_csr_fcsr_Q(r_csr_fcsr_Q[7:5]),
        .r_csr_mie_Q(r_csr_mie_Q),
        .r_csr_mip_Q(r_csr_mip_Q),
        .r_csr_mstatus_Q(r_csr_mstatus_Q[3]),
        .r_ex1_fu_Q(r_ex1_fu_Q),
        .r_ex1_instr_addr_Q(r_ex1_instr_addr_Q),
        .r_ex1_is_rvc_Q(r_ex1_is_rvc_Q),
        .r_ex1_rd_addr_Q(r_ex1_rd_addr_Q),
        .r_ex_bp_addr_Q(r_ex_bp_addr_Q),
        .r_ex_bp_taken_Q(r_ex_bp_taken_Q),
        .r_ex_csr_addr_Q(r_ex_csr_addr_Q),
        .r_ex_exc_tval_Q(r_ex_exc_tval_Q),
        .r_ex_exc_type_Q(r_ex_exc_type_Q),
        .r_ex_exc_valid_Q(r_ex_exc_valid_Q),
        .r_ex_fpu_op_Q(r_ex_fpu_op_Q),
        .r_ex_fu_Q(r_ex_fu_Q),
        .r_ex_fu_s1_source_Q(r_ex_fu_s1_source_Q),
        .r_ex_fu_s2_source_Q(r_ex_fu_s2_source_Q),
        .r_ex_fu_s3_source_Q(r_ex_fu_s3_source_Q),
        .r_ex_imm_Q(r_ex_imm_Q),
        .r_ex_instr_addr_Q(r_ex_instr_addr_Q),
        .r_ex_instr_valid_Q(r_ex_instr_valid_Q),
        .r_ex_is_rvc_Q(r_ex_is_rvc_Q),
        .r_ex_lsu_addr_Q(r_ex_lsu_addr_Q),
        .r_ex_op_Q(r_ex_op_Q),
        .r_ex_rd_addr_Q(r_ex_rd_addr_Q),
        .r_ex_rm_Q(r_ex_rm_Q),
        .r_ex_rs1_addr_Q(r_ex_rs1_addr_Q),
        .r_ex_rs2_addr_Q(r_ex_rs2_addr_Q),
        .r_ex_rs3_addr_Q(r_ex_rs3_addr_Q),
        .r_nmi_i_Q(r_nmi_i_Q),
        .r_nmi_mtval_Q(r_nmi_mtval_Q),
        .r_nmi_source_Q(r_nmi_source_Q),
        .r_prv_Q(r_prv_Q),
        .r_syscall_addr_Q(r_syscall_addr_Q),
        .r_wfi_ce_Q(r_wfi_ce_Q),
        .rf_fr_r1_Q(rf_fr_r1_Q),
        .rf_fr_r2_Q(rf_fr_r2_Q),
        .rf_fr_r3_Q(rf_fr_r3_Q),
        .rf_gpr_r1_Q(rf_gpr_r1_Q),
        .rf_gpr_r2_Q(rf_gpr_r2_Q),
        .s_dm_active_Q(s_dm_active_Q),
        .s_dm_halt_Q(s_dm_halt_Q),
        .s_dm_progbuf_en_Q(s_dm_progbuf_en_Q),
        .s_eviction_error_Q(s_eviction_error_Q),
        .s_ex_bp_restart_Q(s_ex_bp_restart_Q),
        .s_ex_branch_miss_Q(s_ex_branch_miss_Q),
        .s_ex_branch_target_addr_Q(s_ex_branch_target_addr_Q),
        .s_ex_fpu_busy_Q(s_ex_fpu_busy_Q),
        .s_ex_stall_Q(s_ex_stall_Q),
        .s_flush_Q(s_flush_Q),
        .s_rd0_addr_Q(s_rd0_addr_Q),
        .s_rd0_data_Q(s_rd0_data_Q),
        .s_rd0_we_Q(s_rd0_we_Q),
        .s_rd0_write_Q(s_rd0_write_Q),
        .s_rd1_addr_Q(s_rd1_addr_Q),
        .s_rd1_data_Q(s_rd1_data_Q),
        .s_rd1_we_Q(s_rd1_we_Q),
        .s_rd1_write_Q(s_rd1_write_Q),
        .alu_compute_ACT(ex_alu_compute_ACT_wire),
        .alu_s_op_i_D(ex_alu_s_op_i_D_wire),
        .alu_s_s1_data_i_D(ex_alu_s_s1_data_i_D_wire),
        .alu_s_s2_data_i_D(ex_alu_s_s2_data_i_D_wire),
        .b_unit_compute_ACT(ex_b_unit_compute_ACT_wire),
        .b_unit_s_op_i_D(ex_b_unit_s_op_i_D_wire),
        .b_unit_s_s1_data_i_D(ex_b_unit_s_s1_data_i_D_wire),
        .b_unit_s_s2_data_i_D(ex_b_unit_s_s2_data_i_D_wire),
        .bru_compute_ACT(ex_bru_compute_ACT_wire),
        .bru_s_bp_addr_i_D(ex_bru_s_bp_addr_i_D_wire),
        .bru_s_bp_taken_i_D(ex_bru_s_bp_taken_i_D_wire),
        .bru_s_imm_i_D(ex_bru_s_imm_i_D_wire),
        .bru_s_instr_addr_i_D(ex_bru_s_instr_addr_i_D_wire),
        .bru_s_is_rvc_i_D(ex_bru_s_is_rvc_i_D_wire),
        .bru_s_op_i_D(ex_bru_s_op_i_D_wire),
        .bru_s_rs1_data_i_D(ex_bru_s_rs1_data_i_D_wire),
        .bru_s_take_branch_i_D(ex_bru_s_take_branch_i_D_wire),
        .crf_s_csr_addr_i_D(ex_crf_s_csr_addr_i_D_wire),
        .crf_s_csr_re_i_D(ex_crf_s_csr_re_i_D_wire),
        .crf_s_csr_valid_i_D(ex_crf_s_csr_valid_i_D_wire),
        .crf_s_csr_wdata_i_D(ex_crf_s_csr_wdata_i_D_wire),
        .crf_s_csr_we_i_D(ex_crf_s_csr_we_i_D_wire),
        .crf_s_eip_i_D(ex_crf_s_eip_i_D_wire),
        .crf_s_exc_extra_i_D(ex_crf_s_exc_extra_i_D_wire),
        .crf_s_exc_tval_i_D(ex_crf_s_exc_tval_i_D_wire),
        .crf_s_exc_type_i_D(ex_crf_s_exc_type_i_D_wire),
        .crf_s_exc_valid_i_D(ex_crf_s_exc_valid_i_D_wire),
        .crf_s_fflags_i_D(ex_crf_s_fflags_i_D_wire),
        .crf_s_fs_context_change_i_D(ex_crf_s_fs_context_change_i_D_wire),
        .crf_s_fu1_i_D(ex_crf_s_fu1_i_D_wire),
        .crf_s_instr_1_valid_i_D(ex_crf_s_instr_1_valid_i_D_wire),
        .crf_s_instr_addr_i_D(ex_crf_s_instr_addr_i_D_wire),
        .crf_s_instr_valid_excint_i_D(ex_crf_s_instr_valid_excint_i_D_wire),
        .crf_s_instr_valid_i_D(ex_crf_s_instr_valid_i_D_wire),
        .crf_s_int_addr_i_D(ex_crf_s_int_addr_i_D_wire),
        .crf_s_int_safe_to_take_i_D(ex_crf_s_int_safe_to_take_i_D_wire),
        .crf_s_nmi_i_D(ex_crf_s_nmi_i_D_wire),
        .crf_s_nmi_mtval_i_D(ex_crf_s_nmi_mtval_i_D_wire),
        .crf_s_nmi_source_i_D(ex_crf_s_nmi_source_i_D_wire),
        .crf_s_ocd_busy_i_D(ex_crf_s_ocd_busy_i_D_wire),
        .crf_s_ocd_dcsr_i_D(ex_crf_s_ocd_dcsr_i_D_wire),
        .crf_s_ocd_debug_mode_req_i_D(ex_crf_s_ocd_debug_mode_req_i_D_wire),
        .crf_s_ocd_dpc_i_D(ex_crf_s_ocd_dpc_i_D_wire),
        .crf_s_ocd_flush_i_D(ex_crf_s_ocd_flush_i_D_wire),
        .crf_s_ocd_progbuf_mode_i_D(ex_crf_s_ocd_progbuf_mode_i_D_wire),
        .crf_s_ocd_user_mode_req_i_D(ex_crf_s_ocd_user_mode_req_i_D_wire),
        .crf_s_op_i_D(ex_crf_s_op_i_D_wire),
        .crf_s_sip_i_D(ex_crf_s_sip_i_D_wire),
        .crf_s_tip_i_D(ex_crf_s_tip_i_D_wire),
        .crf_s_wfi_delay_i_D(ex_crf_s_wfi_delay_i_D_wire),
        .crf_s_write_fflags_i_D(ex_crf_s_write_fflags_i_D_wire),
        .csr_s_csr_addr_i_D(ex_csr_s_csr_addr_i_D_wire),
        .csr_s_csr_s1_addr_i_D(ex_csr_s_csr_s1_addr_i_D_wire),
        .csr_s_csr_s1_source_i_D(ex_csr_s_csr_s1_source_i_D_wire),
        .csr_s_csr_wdata_i_D(ex_csr_s_csr_wdata_i_D_wire),
        .csr_s_op_i_D(ex_csr_s_op_i_D_wire),
        .div_div_compute_ACT(ex_div_div_compute_ACT_wire),
        .div_s_div_ce_i_D(ex_div_s_div_ce_i_D_wire),
        .div_s_flush_i_D(ex_div_s_flush_i_D_wire),
        .div_s_op_i_D(ex_div_s_op_i_D_wire),
        .div_s_s1_data_i_D(ex_div_s_s1_data_i_D_wire),
        .div_s_s2_data_i_D(ex_div_s_s2_data_i_D_wire),
        .fpu_s_ack_i_D(ex_fpu_s_ack_i_D_wire),
        .fpu_s_exc_type_i_D(ex_fpu_s_exc_type_i_D_wire),
        .fpu_s_exc_valid_i_D(ex_fpu_s_exc_valid_i_D_wire),
        .fpu_s_flush_i_D(ex_fpu_s_flush_i_D_wire),
        .fpu_s_frm_i_D(ex_fpu_s_frm_i_D_wire),
        .fpu_s_instr_addr_i_D(ex_fpu_s_instr_addr_i_D_wire),
        .fpu_s_instr_i_D(ex_fpu_s_instr_i_D_wire),
        .fpu_s_op_i_D(ex_fpu_s_op_i_D_wire),
        .fpu_s_rd_addr_i_D(ex_fpu_s_rd_addr_i_D_wire),
        .fpu_s_rm_i_D(ex_fpu_s_rm_i_D_wire),
        .fpu_s_s1_addr_i_D(ex_fpu_s_s1_addr_i_D_wire),
        .fpu_s_s1_data_i_D(ex_fpu_s_s1_data_i_D_wire),
        .fpu_s_s2_addr_i_D(ex_fpu_s_s2_addr_i_D_wire),
        .fpu_s_s2_data_i_D(ex_fpu_s_s2_data_i_D_wire),
        .fpu_s_s3_addr_i_D(ex_fpu_s_s3_addr_i_D_wire),
        .fpu_s_s3_data_i_D(ex_fpu_s_s3_data_i_D_wire),
        .fpu_s_valid_i_D(ex_fpu_s_valid_i_D_wire),
        .ira_s_ex0_branch_target_i_D(ex_ira_s_ex0_branch_target_i_D_wire),
        .ira_s_ex0_csr_addr_i_D(ex_ira_s_ex0_csr_addr_i_D_wire),
        .ira_s_ex0_instr_addr_i_D(ex_ira_s_ex0_instr_addr_i_D_wire),
        .ira_s_ex0_intexc_addr_i_D(ex_ira_s_ex0_intexc_addr_i_D_wire),
        .ira_s_ex0_is_branch_i_D(ex_ira_s_ex0_is_branch_i_D_wire),
        .ira_s_ex0_is_csr_i_D(ex_ira_s_ex0_is_csr_i_D_wire),
        .ira_s_ex0_is_intexc_i_D(ex_ira_s_ex0_is_intexc_i_D_wire),
        .ira_s_ex0_is_rvc_i_D(ex_ira_s_ex0_is_rvc_i_D_wire),
        .ira_s_ex0_retired_i_D(ex_ira_s_ex0_retired_i_D_wire),
        .ira_s_ex1_instr_addr_i_D(ex_ira_s_ex1_instr_addr_i_D_wire),
        .ira_s_ex1_is_rvc_i_D(ex_ira_s_ex1_is_rvc_i_D_wire),
        .ira_s_ex1_retired_i_D(ex_ira_s_ex1_retired_i_D_wire),
        .ira_s_ocd_addr_i_D(ex_ira_s_ocd_addr_i_D_wire),
        .ira_s_ocd_stop_count_i_D(ex_ira_s_ocd_stop_count_i_D_wire),
        .ira_s_ocd_valid_i_D(ex_ira_s_ocd_valid_i_D_wire),
        .lsu_s_addr_i_D(ex_lsu_s_addr_i_D_wire),
        .lsu_s_clear_i_D(ex_lsu_s_clear_i_D_wire),
        .lsu_s_ocd_mmode_i_D(ex_lsu_s_ocd_mmode_i_D_wire),
        .lsu_s_op_i_D(ex_lsu_s_op_i_D_wire),
        .lsu_s_rd_addr_i_D(ex_lsu_s_rd_addr_i_D_wire),
        .lsu_s_syscall_addr_i_D(ex_lsu_s_syscall_addr_i_D_wire),
        .lsu_s_wdata_i_D(ex_lsu_s_wdata_i_D_wire),
        .mul_compute_ACT(ex_mul_compute_ACT_wire),
        .mul_s_op_i_D(ex_mul_s_op_i_D_wire),
        .mul_s_s1_data_i_D(ex_mul_s_s1_data_i_D_wire),
        .mul_s_s2_data_i_D(ex_mul_s_s2_data_i_D_wire),
        .ocd_s_dm_active_i_D(ex_ocd_s_dm_active_i_D_wire),
        .ocd_s_dm_halt_i_D(ex_ocd_s_dm_halt_i_D_wire),
        .ocd_s_dm_progbuf_en_i_D(ex_ocd_s_dm_progbuf_en_i_D_wire),
        .ocd_s_exc_type_i_D(ex_ocd_s_exc_type_i_D_wire),
        .ocd_s_exc_valid_i_D(ex_ocd_s_exc_valid_i_D_wire),
        .ocd_s_instr_addr_i_D(ex_ocd_s_instr_addr_i_D_wire),
        .ocd_s_instr_commit_i_D(ex_ocd_s_instr_commit_i_D_wire),
        .ocd_s_instr_valid_i_D(ex_ocd_s_instr_valid_i_D_wire),
        .r_ex1_fu_D(r_ex1_fu_D),
        .r_ex1_fu_WE(r_ex1_fu_WE),
        .r_ex1_instr_addr_D(r_ex1_instr_addr_D),
        .r_ex1_instr_addr_WE(r_ex1_instr_addr_WE),
        .r_ex1_is_rvc_D(r_ex1_is_rvc_D),
        .r_ex1_is_rvc_WE(r_ex1_is_rvc_WE),
        .r_ex1_rd_addr_D(r_ex1_rd_addr_D),
        .r_ex1_rd_addr_WE(r_ex1_rd_addr_WE),
        .r_nmi_i_D(r_nmi_i_D),
        .r_nmi_i_WE(r_nmi_i_WE),
        .r_nmi_mtval_D(r_nmi_mtval_D),
        .r_nmi_mtval_WE(r_nmi_mtval_WE),
        .r_nmi_source_D(r_nmi_source_D),
        .r_nmi_source_WE(r_nmi_source_WE),
        .r_wfi_ce_D(r_wfi_ce_D),
        .r_wfi_ce_WE(r_wfi_ce_WE),
        .rf_fr_r1_RA(rf_fr_r1_RA),
        .rf_fr_r1_RE(rf_fr_r1_RE),
        .rf_fr_r2_RA(rf_fr_r2_RA),
        .rf_fr_r2_RE(rf_fr_r2_RE),
        .rf_fr_r3_RA(rf_fr_r3_RA),
        .rf_fr_r3_RE(rf_fr_r3_RE),
        .rf_fr_w_D(rf_fr_w_D),
        .rf_fr_w_WA(rf_fr_w_WA),
        .rf_fr_w_WE(rf_fr_w_WE),
        .rf_gpr_r1_RA(rf_gpr_r1_RA),
        .rf_gpr_r1_RE(rf_gpr_r1_RE),
        .rf_gpr_r2_RA(rf_gpr_r2_RA),
        .rf_gpr_r2_RE(rf_gpr_r2_RE),
        .rf_gpr_w0_D(rf_gpr_w0_D),
        .rf_gpr_w0_WA(rf_gpr_w0_WA),
        .rf_gpr_w0_WE(rf_gpr_w0_WE),
        .rf_gpr_w1_D(rf_gpr_w1_D),
        .rf_gpr_w1_WA(rf_gpr_w1_WA),
        .rf_gpr_w1_WE(rf_gpr_w1_WE),
        .s_dm_progbuf_done_D(s_dm_progbuf_done_D),
        .s_dm_progbuf_exc_D(s_dm_progbuf_exc_D),
        .s_ex1_clear_D(s_ex1_clear_D),
        .s_ex1_stall_D(s_ex1_stall_D),
        .s_ex_bp_flush_D(s_ex_bp_flush_D),
        .s_ex_bp_flush_line_D(s_ex_bp_flush_line_D),
        .s_ex_bp_restart_D(s_ex_bp_restart_D),
        .s_ex_branch_bht_update_D(s_ex_branch_bht_update_D),
        .s_ex_branch_btb_update_D(s_ex_branch_btb_update_D),
        .s_ex_branch_instr_addr_D(s_ex_branch_instr_addr_D),
        .s_ex_branch_is_rvc_D(s_ex_branch_is_rvc_D),
        .s_ex_branch_miss_D(s_ex_branch_miss_D),
        .s_ex_branch_offset_D(s_ex_branch_offset_D),
        .s_ex_branch_taken_D(s_ex_branch_taken_D),
        .s_ex_branch_target_addr_D(s_ex_branch_target_addr_D),
        .s_ex_clear_D(s_ex_clear_D),
        .s_ex_fence_valid_D(s_ex_fence_valid_D),
        .s_ex_fpu_busy_D(s_ex_fpu_busy_D),
        .s_ex_p0_addr_D(s_ex_p0_addr_D),
        .s_ex_p0_we_D(s_ex_p0_we_D),
        .s_ex_p1_addr_D(s_ex_p1_addr_D),
        .s_ex_p1_we_D(s_ex_p1_we_D),
        .s_ex_progbuf_mode_D(s_ex_progbuf_mode_D),
        .s_ex_rd_addr_D(s_ex_rd_addr_D),
        .s_ex_rd_data_D(s_ex_rd_data_D),
        .s_ex_rd_we_D(s_ex_rd_we_D),
        .s_ex_return_link_D(s_ex_return_link_D),
        .s_ex_return_update_D(s_ex_return_update_D),
        .s_ex_stall_D(s_ex_stall_D),
        .s_flush_D(s_flush_D),
        .s_fpu_dst_regs_D(s_fpu_dst_regs_D),
        .s_hart_halted_D(s_hart_halted_D),
        .s_perf_branch_miss_D(s_perf_branch_miss_D),
        .s_perf_csr_flush_D(s_perf_csr_flush_D),
        .s_perf_div_stall_D(s_perf_div_stall_D),
        .s_perf_exc_flush_D(s_perf_exc_flush_D),
        .s_perf_fpu_stall_D(s_perf_fpu_stall_D),
        .s_perf_int_flush_D(s_perf_int_flush_D),
        .s_perf_lsu_stall_D(s_perf_lsu_stall_D),
        .s_perf_waddr_D(s_perf_waddr_D),
        .s_perf_wdata_D(s_perf_wdata_D),
        .s_perf_we_D(s_perf_we_D),
        .s_progbuf_mode_active_D(s_progbuf_mode_active_D),
        .s_rd0_addr_D(s_rd0_addr_D),
        .s_rd0_data_D(s_rd0_data_D),
        .s_rd0_we_D(s_rd0_we_D),
        .s_rd0_write_D(s_rd0_write_D),
        .s_rd1_addr_D(s_rd1_addr_D),
        .s_rd1_data_D(s_rd1_data_D),
        .s_rd1_we_D(s_rd1_we_D),
        .s_rd1_write_D(s_rd1_write_D),
        .s_wfi_prevent_fetch_D(s_wfi_prevent_fetch_D)
    );

endmodule: codix_berkelium_ca_core_execute_stage_t
